/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:21 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDNFCSEOSRemovedEvent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _reason;
	NSData* _uuidReference;
	BOOL _hasCardEmulationStarted;
	BOOL _hasExpressTransactionStarted;
	SCD_Struct_AW2 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                      //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasReason; 
@property (assign,nonatomic) unsigned reason;                                   //@synthesize reason=_reason - In the implementation block
@property (nonatomic,readonly) BOOL hasUuidReference; 
@property (nonatomic,retain) NSData * uuidReference;                            //@synthesize uuidReference=_uuidReference - In the implementation block
@property (assign,nonatomic) BOOL hasHasExpressTransactionStarted; 
@property (assign,nonatomic) BOOL hasExpressTransactionStarted;                 //@synthesize hasExpressTransactionStarted=_hasExpressTransactionStarted - In the implementation block
@property (assign,nonatomic) BOOL hasHasCardEmulationStarted; 
@property (assign,nonatomic) BOOL hasCardEmulationStarted;                      //@synthesize hasCardEmulationStarted=_hasCardEmulationStarted - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)reason;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasReason:(BOOL)arg1 ;
-(BOOL)hasReason;
-(void)setReason:(unsigned)arg1 ;
-(void)setUuidReference:(NSData *)arg1 ;
-(BOOL)hasUuidReference;
-(NSData *)uuidReference;
-(void)setHasExpressTransactionStarted:(BOOL)arg1 ;
-(void)setHasHasExpressTransactionStarted:(BOOL)arg1 ;
-(BOOL)hasHasExpressTransactionStarted;
-(void)setHasCardEmulationStarted:(BOOL)arg1 ;
-(void)setHasHasCardEmulationStarted:(BOOL)arg1 ;
-(BOOL)hasHasCardEmulationStarted;
-(BOOL)hasExpressTransactionStarted;
-(BOOL)hasCardEmulationStarted;
@end

