/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:22 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCTSMConnectivityExceptionEvent, NSString;

@interface NFAWDTSMConnectivityException : NSObject <NFAWDEventProtocol> {

	unsigned _errorCode;
	AWDNFCTSMConnectivityExceptionEvent* _metric;

}

@property (assign,nonatomic) unsigned errorCode;                                        //@synthesize errorCode=_errorCode - In the implementation block
@property (nonatomic,retain) AWDNFCTSMConnectivityExceptionEvent * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(void)setErrorCode:(unsigned)arg1 ;
-(unsigned)errorCode;
-(unsigned)getMetricId;
-(id)getMetric;
-(void)updateExceptionUUID:(id)arg1 ;
-(void)setMetric:(AWDNFCTSMConnectivityExceptionEvent *)arg1 ;
-(AWDNFCTSMConnectivityExceptionEvent *)metric;
@end

