/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:22 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCSERemovedEvent, NSString;

@interface NFAWDSERemoved : NSObject <NFAWDEventProtocol> {

	BOOL _hasCardEmulationStarted;
	AWDNFCSERemovedEvent* _metric;

}

@property (assign,nonatomic) unsigned reason; 
@property (assign,nonatomic) BOOL hasCardEmulationStarted;               //@synthesize hasCardEmulationStarted=_hasCardEmulationStarted - In the implementation block
@property (nonatomic,retain) AWDNFCSERemovedEvent * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(unsigned)reason;
-(void)setReason:(unsigned)arg1 ;
-(void)setHasCardEmulationStarted:(BOOL)arg1 ;
-(BOOL)hasCardEmulationStarted;
-(unsigned)getMetricId;
-(id)getMetric;
-(void)updateExceptionUUID:(id)arg1 ;
-(BOOL)hasCardemulationStarted;
-(void)setHasCardemulationStarted:(BOOL)arg1 ;
-(void)setMetric:(AWDNFCSERemovedEvent *)arg1 ;
-(AWDNFCSERemovedEvent *)metric;
@end

