/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:22 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCVersions, NSString;

@interface NFAWDVersionInfo : NSObject <NFAWDEventProtocol> {

	unsigned _nfccHWVersion;
	unsigned _nfccROMVersion;
	unsigned _nfccFWVersion;
	unsigned _nfccFWRevision;
	unsigned _nfccMWVersion;
	unsigned _seDeviceType;
	unsigned _seHWVersion;
	unsigned _seFWVersion;
	unsigned _seSignKeyType;
	unsigned _seSeqCount;
	unsigned _seRefCount;
	unsigned _seOSMode;
	unsigned _seRestrictedMode;
	unsigned _seMigrationState;
	unsigned _seMigrationPkgs;
	unsigned _seMigrationInst;
	unsigned _seosHWVersion;
	unsigned _seosOSVersion;
	unsigned _seosOSMode;
	unsigned _seosSignKeyType;
	unsigned _seosMigrationState;
	AWDNFCVersions* _metric;

}

@property (assign,nonatomic) unsigned nfccHWVersion;                   //@synthesize nfccHWVersion=_nfccHWVersion - In the implementation block
@property (assign,nonatomic) unsigned nfccROMVersion;                  //@synthesize nfccROMVersion=_nfccROMVersion - In the implementation block
@property (assign,nonatomic) unsigned nfccFWVersion;                   //@synthesize nfccFWVersion=_nfccFWVersion - In the implementation block
@property (assign,nonatomic) unsigned nfccFWRevision;                  //@synthesize nfccFWRevision=_nfccFWRevision - In the implementation block
@property (assign,nonatomic) unsigned nfccMWVersion;                   //@synthesize nfccMWVersion=_nfccMWVersion - In the implementation block
@property (nonatomic,retain) NSString * sePlatformId; 
@property (assign,nonatomic) unsigned seDeviceType;                    //@synthesize seDeviceType=_seDeviceType - In the implementation block
@property (assign,nonatomic) unsigned seHWVersion;                     //@synthesize seHWVersion=_seHWVersion - In the implementation block
@property (assign,nonatomic) unsigned seFWVersion;                     //@synthesize seFWVersion=_seFWVersion - In the implementation block
@property (assign,nonatomic) unsigned seSignKeyType;                   //@synthesize seSignKeyType=_seSignKeyType - In the implementation block
@property (assign,nonatomic) unsigned seSeqCount;                      //@synthesize seSeqCount=_seSeqCount - In the implementation block
@property (assign,nonatomic) unsigned seRefCount;                      //@synthesize seRefCount=_seRefCount - In the implementation block
@property (assign,nonatomic) unsigned seOSMode;                        //@synthesize seOSMode=_seOSMode - In the implementation block
@property (assign,nonatomic) unsigned seRestrictedMode;                //@synthesize seRestrictedMode=_seRestrictedMode - In the implementation block
@property (assign,nonatomic) unsigned seMigrationState;                //@synthesize seMigrationState=_seMigrationState - In the implementation block
@property (assign,nonatomic) unsigned seMigrationPkgs;                 //@synthesize seMigrationPkgs=_seMigrationPkgs - In the implementation block
@property (assign,nonatomic) unsigned seMigrationInst;                 //@synthesize seMigrationInst=_seMigrationInst - In the implementation block
@property (nonatomic,retain) NSString * seosPlatformID; 
@property (assign,nonatomic) unsigned seosHWVersion;                   //@synthesize seosHWVersion=_seosHWVersion - In the implementation block
@property (assign,nonatomic) unsigned seosOSVersion;                   //@synthesize seosOSVersion=_seosOSVersion - In the implementation block
@property (assign,nonatomic) unsigned seosOSMode;                      //@synthesize seosOSMode=_seosOSMode - In the implementation block
@property (assign,nonatomic) unsigned seosSignKeyType;                 //@synthesize seosSignKeyType=_seosSignKeyType - In the implementation block
@property (assign,nonatomic) unsigned seosMigrationState;              //@synthesize seosMigrationState=_seosMigrationState - In the implementation block
@property (nonatomic,retain) AWDNFCVersions * metric;                  //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(void)setSeosPlatformID:(NSString *)arg1 ;
-(void)setNfccHWVersion:(unsigned)arg1 ;
-(void)setNfccROMVersion:(unsigned)arg1 ;
-(void)setNfccFWVersion:(unsigned)arg1 ;
-(void)setNfccFWRevision:(unsigned)arg1 ;
-(void)setSeDeviceType:(unsigned)arg1 ;
-(void)setSeHWVersion:(unsigned)arg1 ;
-(void)setSeFWVersion:(unsigned)arg1 ;
-(void)setSeSignKeyType:(unsigned)arg1 ;
-(void)setSeOSMode:(unsigned)arg1 ;
-(void)setSeRestrictedMode:(unsigned)arg1 ;
-(void)setSeMigrationState:(unsigned)arg1 ;
-(void)setSeMigrationPkgs:(unsigned)arg1 ;
-(void)setSeMigrationInst:(unsigned)arg1 ;
-(void)setSeosHWVersion:(unsigned)arg1 ;
-(void)setSeosOSVersion:(unsigned)arg1 ;
-(void)setSeosOSMode:(unsigned)arg1 ;
-(void)setSeosSignKeyType:(unsigned)arg1 ;
-(void)setSeosMigrationState:(unsigned)arg1 ;
-(unsigned)nfccHWVersion;
-(unsigned)nfccROMVersion;
-(unsigned)nfccFWVersion;
-(unsigned)nfccFWRevision;
-(unsigned)seDeviceType;
-(unsigned)seHWVersion;
-(unsigned)seFWVersion;
-(unsigned)seSignKeyType;
-(unsigned)seOSMode;
-(unsigned)seRestrictedMode;
-(unsigned)seMigrationState;
-(unsigned)seMigrationPkgs;
-(unsigned)seMigrationInst;
-(NSString *)seosPlatformID;
-(unsigned)seosHWVersion;
-(unsigned)seosOSVersion;
-(unsigned)seosOSMode;
-(unsigned)seosSignKeyType;
-(unsigned)seosMigrationState;
-(unsigned)getMetricId;
-(id)getMetric;
-(void)setNfccMWVersion:(unsigned)arg1 ;
-(void)setSePlatformId:(NSString *)arg1 ;
-(NSString *)sePlatformId;
-(void)setSeSeqCount:(unsigned)arg1 ;
-(void)setSeRefCount:(unsigned)arg1 ;
-(unsigned)nfccMWVersion;
-(unsigned)seSeqCount;
-(unsigned)seRefCount;
-(void)setMetric:(AWDNFCVersions *)arg1 ;
-(AWDNFCVersions *)metric;
@end

