/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:22 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFCurrency : NSObject
+(unsigned long long)decodeBCDAmount:(id)arg1 ;
+(id)encodeBCDAmount:(unsigned long long)arg1 ;
+(id)getCurrencyStringCodeFromNumericCode:(unsigned)arg1 ;
+(int)getFractionDigitsFromCurrencyStringCode:(id)arg1 ;
@end

