/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:22 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface NFTimer : NSObject {

	unsigned _index;
	/*^block*/id _block;
	NSObject*<OS_dispatch_queue> _queue;

}
-(void)stopTimer;
-(void)dealloc;
-(id)initWithCallback:(/*^block*/id)arg1 queue:(id)arg2 ;
-(void)startTimer:(double)arg1 ;
@end

