/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:21 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFWeakReference : NSObject {

	id _store;

}
+(id)weakReferenceWithObject:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)setObject:(id)arg1 ;
-(id)initWithObject:(id)arg1 ;
-(id)getObject;
@end

