/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:16 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __IDXIndex* IDXIndexRef;

typedef struct __CFURL* CFURLRef;

typedef struct _NSZone* NSZoneRef;

typedef struct __CFString* CFStringRef;

typedef struct __CFArray* CFArrayRef;

typedef struct {
	long long field1;
	long long field2;
} SCD_Struct_Me5;

typedef struct {
	unsigned long long field1;
	unsigned long long field2;
} SCD_Struct_Me6;

