/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:16 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libmecabra.dylib/libmecabra.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDictionary;

@interface MecabraCandidate : NSObject <NSCopying> {

	void* _rawCandidate;

}

@property (nonatomic,readonly) MecabraCandidateBase* rawCandidate; 
@property (nonatomic,readonly) ConversionCandidate* rawConversionCandidate; 
@property (nonatomic,readonly) BOOL isConversionCandidate; 
@property (nonatomic,readonly) BOOL isSyntheticCandidate; 
@property (nonatomic,readonly) BOOL isExtensionCandidate; 
@property (nonatomic,readonly) BOOL isEmojiCandidate; 
@property (nonatomic,readonly) BOOL isPersonName; 
@property (nonatomic,readonly) BOOL isLearningDictionaryCandidate; 
@property (nonatomic,readonly) BOOL isUserWordCandidate; 
@property (nonatomic,readonly) BOOL isPredictionCandidate; 
@property (nonatomic,readonly) BOOL isFuzzyMatchCandidate; 
@property (nonatomic,readonly) BOOL isAutocorrectedCandidate; 
@property (nonatomic,readonly) int type; 
@property (nonatomic,readonly) unsigned long long wordCount; 
@property (nonatomic,readonly) NSString * surface; 
@property (nonatomic,readonly) NSString * string; 
@property (nonatomic,readonly) NSString * category; 
@property (nonatomic,readonly) NSString * analysisString; 
@property (nonatomic,readonly) NSString * convertedAnalysisString; 
@property (nonatomic,readonly) NSString * dictionaryReading; 
@property (nonatomic,readonly) NSDictionary * attributes; 
+(id)syntheticCandidateFromWords:(id)arg1 withLexicon:(Lexicon*)arg2 language:(int)arg3 ;
-(unsigned short)matchType;
-(BOOL)isEmojiCandidate;
-(id)initWithCandidate:(MecabraCandidateBase*)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(BOOL)setDisplayString:(CFStringRef)arg1 ;
-(NSString *)category;
-(int)type;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)string;
-(BOOL)isExtensionCandidate;
-(NSDictionary *)attributes;
-(unsigned short)kind;
-(id)words;
-(long long)weight;
-(void)setWeight:(unsigned long long)arg1 ;
-(ConversionCandidate*)rawConversionCandidate;
-(NSString *)dictionaryReading;
-(BOOL)isConversionCandidate;
-(MecabraCandidateBase*)rawCandidate;
-(NSString *)analysisString;
-(unsigned short)matchedLengthType;
-(NSString *)convertedAnalysisString;
-(BOOL)isPersonName;
-(BOOL)isLearningDictionaryCandidate;
-(BOOL)isUserWordCandidate;
-(BOOL)isPredictionCandidate;
-(BOOL)isFuzzyMatchCandidate;
-(BOOL)isAutocorrectedCandidate;
-(long long)phraseBoundaryAfterWordAtIndex:(long long)arg1 ;
-(unsigned short)wordLengthAtIndex:(unsigned long long)arg1 ;
-(unsigned short)wordReadingLengthAtIndex:(unsigned long long)arg1 ;
-(unsigned short)wordDictionaryReadingLengthAtIndex:(unsigned long long)arg1 ;
-(BOOL)wordIsFromSystemDictionaryAtIndex:(unsigned long long)arg1 ;
-(CFArrayRef)copySyllableLengthArrayForWordAtIndex:(unsigned long long)arg1 ;
-(unsigned short)lcAttrAtIndex:(unsigned long long)arg1 ;
-(unsigned short)rcAttrAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)trieValueAtIndex:(unsigned long long)arg1 ;
-(unsigned short)lastPrefixValue;
-(CFArrayRef)copySyllableLengthArrayInAnalysisString;
-(CFArrayRef)copySyllableLengthArrayInConvertedAnalysisString;
-(CFArrayRef)copySyllableLengthArrayInDictionaryReading;
-(SCD_Struct_Me5)wordRangeAtIndex:(long long)arg1 ;
-(id)syllablesInAnalysisString;
-(id)syllablesInConvertedAnalysisString;
-(id)syllablesInDictionaryReading;
-(id)syllablesInString:(id)arg1 syllableLengths:(id)arg2 ;
-(BOOL)isSyntheticCandidate;
-(id)convertedAnalysisStringForFirstSyllable;
-(id)syllabifiedAnalysisString;
-(id)syllabifiedConvertedAnalysisString;
-(id)syllabifiedDictionaryReading;
-(id)wordReadings;
-(unsigned long long)wordCount;
-(NSString *)surface;
-(id)wordIDs;
@end

