/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/AEAnnotationTheme.h>

@interface AEAnnotationThemeUnderline : AEAnnotationTheme
-(id)highlightColor;
-(int)annotationStyle;
-(id)noteFillColor;
-(id)noteBorderColor;
-(id)noteTextColor;
-(id)noteMarkerFillColor;
-(id)noteMarkerBorderColor;
-(id)notesSidebarBarColor;
-(BOOL)isUnderline;
@end

