/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:24 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/AEUserPublishingLookUpRequest.h>

@protocol AEUserPublishingLookUpRequest <NSObject>
@required
+(id)resultsDictionaryFromLookUpResponse:(id)arg1;
+(id)expirationDateFromLookUpResponse:(id)arg1;
+(BOOL)isEnabled;
-(id)initWithAdamIDs:(id)arg1 keyProfile:(id)arg2 protocolVersion:(id)arg3;
-(void)cancel;
-(BOOL)startWithLookupBlock:(/*^block*/id)arg1;

@end


@class SSLookupRequest, NSString;

@interface AEUserPublishingLookUpRequest : NSObject <AEUserPublishingLookUpRequest> {

	SSLookupRequest* _request;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)keyProfileFromAEKeyProfile:(id)arg1 ;
+(id)resultsDictionaryFromLookUpResponse:(id)arg1 ;
+(id)expirationDateFromLookUpResponse:(id)arg1 ;
+(BOOL)isEnabled;
-(id)initWithAdamIDs:(id)arg1 keyProfile:(id)arg2 protocolVersion:(id)arg3 ;
-(void)cancel;
-(BOOL)startWithLookupBlock:(/*^block*/id)arg1 ;
@end

