/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <IMCommonCore/IMCommonCore-Structs.h>
@class NSString, NSMutableSet, NSObject, NSMutableDictionary, NSOperationQueue, IMMappedKeyDataStore, IMPersistentInterestMap, IMCoalescingCallBlock;

@interface BCCoverCache : NSObject {

	CGSize _intermediateSize;
	NSString* _identifier;
	NSMutableSet* _negativeCache;
	BOOL _paused;
	NSObject*<OS_dispatch_queue> _negativeSync;
	NSObject*<OS_dispatch_queue> _activeCoversSync;
	NSMutableDictionary* _activeCoverSourcesByBookId;
	NSMutableDictionary* _activeSeriesSourcesBySeriesId;
	BOOL _activeSourcesCleanupScheduled;
	os_unfair_lock_s _activeSourceCleanupSpinlock;
	BOOL _forceGenericCovers;
	BOOL _forceBlankCovers;
	BOOL _disableCoverCleanup;
	NSOperationQueue* _renderQueue;
	NSMutableDictionary* _temporaryArtUrls;
	IMMappedKeyDataStore* _mappedCoverCache;
	NSObject*<OS_dispatch_queue> _prefetchReplyQueue;
	NSObject*<OS_dispatch_queue> _keyReplyQueue;
	NSObject*<OS_dispatch_queue> _dataReplyQueue;
	NSObject*<OS_dispatch_queue> _refreshQueue;
	NSObject*<OS_dispatch_queue> _cleanupQueue;
	NSObject*<OS_dispatch_queue> _timeoutQueue;
	NSObject*<OS_dispatch_queue> _evictionQueue;
	IMPersistentInterestMap* _sponsorInterest;
	IMCoalescingCallBlock* _coalescedEviction;

}

@property (readonly) NSOperationQueue * renderQueue;                                         //@synthesize renderQueue=_renderQueue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * temporaryArtUrls;                         //@synthesize temporaryArtUrls=_temporaryArtUrls - In the implementation block
@property (nonatomic,readonly) IMMappedKeyDataStore * mappedCoverCache;                      //@synthesize mappedCoverCache=_mappedCoverCache - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> prefetchReplyQueue;              //@synthesize prefetchReplyQueue=_prefetchReplyQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> keyReplyQueue;                   //@synthesize keyReplyQueue=_keyReplyQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> dataReplyQueue;                  //@synthesize dataReplyQueue=_dataReplyQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> refreshQueue;                    //@synthesize refreshQueue=_refreshQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> cleanupQueue;                    //@synthesize cleanupQueue=_cleanupQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> timeoutQueue;                    //@synthesize timeoutQueue=_timeoutQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> evictionQueue;                   //@synthesize evictionQueue=_evictionQueue - In the implementation block
@property (nonatomic,readonly) IMPersistentInterestMap * sponsorInterest;                    //@synthesize sponsorInterest=_sponsorInterest - In the implementation block
@property (nonatomic,retain) IMCoalescingCallBlock * coalescedEviction;                      //@synthesize coalescedEviction=_coalescedEviction - In the implementation block
@property (assign,nonatomic) BOOL forceGenericCovers;                                        //@synthesize forceGenericCovers=_forceGenericCovers - In the implementation block
@property (assign,nonatomic) BOOL forceBlankCovers;                                          //@synthesize forceBlankCovers=_forceBlankCovers - In the implementation block
@property (assign,nonatomic) BOOL disableCoverCleanup;                                       //@synthesize disableCoverCleanup=_disableCoverCleanup - In the implementation block
@property (assign) CGSize intermediateSize;                                                  //@synthesize intermediateSize=_intermediateSize - In the implementation block
+(void)_cleanPreviousSharedCaches;
+(id)cachesDirectoryPath;
+(id)imageCacheDirectoryPath;
+(id)coverCacheDirectoryPath;
+(id)mappedCachePath;
+(id)sharedInstance;
-(id)storeImage:(id)arg1 bookId:(id)arg2 cachePrefix:(id)arg3 size:(CGSize)arg4 xattrs:(id)arg5 writeToDisk:(BOOL)arg6 format:(int)arg7 options:(int)arg8 ;
-(id)fetchImageForBookId:(id)arg1 prefix:(id)arg2 size:(CGSize)arg3 options:(int)arg4 ;
-(BOOL)negativeCacheContainsEntryForBookId:(id)arg1 ;
-(CGSize)intermediateSize;
-(NSObject*<OS_dispatch_queue>)refreshQueue;
-(NSObject*<OS_dispatch_queue>)cleanupQueue;
-(BOOL)forceBlankCovers;
-(NSObject*<OS_dispatch_queue>)timeoutQueue;
-(BOOL)forceGenericCovers;
-(NSObject*<OS_dispatch_queue>)prefetchReplyQueue;
-(id)_artForBook:(id)arg1 size:(CGSize)arg2 withCachePrefix:(id)arg3 options:(int)arg4 ;
-(id)_largestCoverArtExceptGenericForBookID:(id)arg1 options:(int)arg2 ;
-(id)_tempCoverArtForBookWithID:(id)arg1 size:(CGSize)arg2 options:(int)arg3 ;
-(id)_prefetchWithOptions:(int)arg1 ;
-(id)_mappedKeyForBookId:(id)arg1 prefix:(id)arg2 size:(CGSize)arg3 options:(int)arg4 ;
-(IMMappedKeyDataStore *)mappedCoverCache;
-(NSObject*<OS_dispatch_queue>)dataReplyQueue;
-(void)removeNegativeResultForBookId:(id)arg1 ;
-(void)registerNegativeResultForBookId:(id)arg1 ;
-(id)_urlForImageCacheWithBookId:(id)arg1 cachePrefix:(id)arg2 size:(CGSize)arg3 options:(int)arg4 ;
-(void)storeGenericCoverArtImage:(id)arg1 forDatabaseKey:(id)arg2 size:(CGSize)arg3 xattrs:(id)arg4 format:(int)arg5 options:(int)arg6 ;
-(void)scheduleSourceCleanup;
-(id)coverSourceForInfo:(id)arg1 resolver:(id)arg2 size:(CGSize)arg3 options:(int)arg4 identifier:(id)arg5 ;
-(void)_evictUnsponsoredCoversWithCompletion:(/*^block*/id)arg1 ;
-(id)_sourceBookIdFromKey:(id)arg1 ;
-(void)_refreshActiveCovers;
-(id)_mappedKeyPrefixForBookId:(id)arg1 prefix:(id)arg2 ;
-(NSObject*<OS_dispatch_queue>)keyReplyQueue;
-(id)_mappedKeyPrefixForBookId:(id)arg1 ;
-(id)_largestKeyForKeys:(id)arg1 ;
-(CGSize)_mappedKeySize:(id)arg1 ;
-(id)_sourceKeyForBook:(id)arg1 size:(CGSize)arg2 options:(int)arg3 ;
-(id)_sourceKeyForSeries:(id)arg1 size:(CGSize)arg2 options:(int)arg3 ;
-(void)_cleanupActiveCoverSources;
-(id)_sourceKeyPrefixForBookId:(id)arg1 ;
-(void)clearCacheForBookID:(id)arg1 ;
-(id)_mappedBookIdFromKey:(id)arg1 ;
-(void)removeNegativeResultForBookIds:(id)arg1 notify:(BOOL)arg2 ;
-(void)clearCacheForBookIDs:(id)arg1 ;
-(void)_refreshSourceForBookId:(id)arg1 temporaryItemIdentifier:(id)arg2 ;
-(id)fetchImageForKey:(id)arg1 options:(int)arg2 ;
-(BOOL)isGenericCoverAtURL:(id)arg1 ;
-(BOOL)isGenericCoverWithData:(id)arg1 ;
-(void)_fetchImageUrl:(id)arg1 forItemID:(id)arg2 format:(int)arg3 ;
-(void)removeNegativeResultForBookId:(id)arg1 notify:(BOOL)arg2 ;
-(IMPersistentInterestMap *)sponsorInterest;
-(IMCoalescingCallBlock *)coalescedEviction;
-(void)refreshSeriesWithIDs:(id)arg1 ;
-(void)setForceGenericCovers:(BOOL)arg1 ;
-(void)setForceBlankCovers:(BOOL)arg1 ;
-(id)seriesSourceForInfo:(id)arg1 resolver:(id)arg2 size:(CGSize)arg3 options:(int)arg4 identifier:(id)arg5 ;
-(void)refreshArtForBookID:(id)arg1 url:(id)arg2 resolver:(id)arg3 ;
-(void)clearPersistentCacheForBookIDs:(id)arg1 ;
-(void)storeTemporaryImage:(id)arg1 forItemId:(id)arg2 fetchURL:(id)arg3 ;
-(void)registerInterestingIdentifiers:(id)arg1 forSponsor:(id)arg2 ;
-(void)setIntermediateSize:(CGSize)arg1 ;
-(NSMutableDictionary *)temporaryArtUrls;
-(void)setTemporaryArtUrls:(NSMutableDictionary *)arg1 ;
-(void)setCoalescedEviction:(IMCoalescingCallBlock *)arg1 ;
-(BOOL)disableCoverCleanup;
-(void)setDisableCoverCleanup:(BOOL)arg1 ;
-(id)init;
-(void)dealloc;
-(void)reset;
-(id)initWithIdentifier:(id)arg1 ;
-(void)didReceiveMemoryWarning:(id)arg1 ;
-(void)cache:(id)arg1 willEvictObject:(id)arg2 ;
-(void)cancelPendingRenderOperations;
-(NSOperationQueue *)renderQueue;
-(NSObject*<OS_dispatch_queue>)evictionQueue;
@end

