/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface BCUserAccount : NSObject {

	BOOL _cachedIsPrimaryAccountManagedAppleID;
	BOOL _cachedValuePrewarmed;
	NSObject*<OS_dispatch_queue> _prewarmQueue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> prewarmQueue;              //@synthesize prewarmQueue=_prewarmQueue - In the implementation block
@property (assign,nonatomic) BOOL cachedIsPrimaryAccountManagedAppleID;              //@synthesize cachedIsPrimaryAccountManagedAppleID=_cachedIsPrimaryAccountManagedAppleID - In the implementation block
@property (assign,nonatomic) BOOL cachedValuePrewarmed;                              //@synthesize cachedValuePrewarmed=_cachedValuePrewarmed - In the implementation block
+(BOOL)isPrimaryAccountManagedAppleID;
+(BOOL)isUserSignedInToiTunes;
+(id)sharedInstance;
+(id)storeAccountID;
+(id)storeFrontIdentifier;
+(void)prewarm;
+(BOOL)isUserSignedInToiCloud;
-(NSObject*<OS_dispatch_queue>)prewarmQueue;
-(void)setCachedValuePrewarmed:(BOOL)arg1 ;
-(BOOL)_evaluateIsPrimaryAccountManagedAppleID;
-(void)setCachedIsPrimaryAccountManagedAppleID:(BOOL)arg1 ;
-(BOOL)_isPrimaryAccountManagedAppleID;
-(BOOL)cachedValuePrewarmed;
-(BOOL)cachedIsPrimaryAccountManagedAppleID;
-(void)setPrewarmQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(void)_prewarm;
@end

