/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <IMCommonCore/IMCommonCore-Structs.h>
@interface IMAccessibilitySafeCategory : NSObject
+(id)imaxTargetClassName;
+(Class)imaxBaseSafeCategoryClass;
+(void)_imaxInitializeSafeCategory;
+(void)_imaxInstallSafeCategoryOnClass:(Class)arg1 ;
+(void)_imaxInstallSafeCategoryOnClassNamed:(id)arg1 ;
+(void)_imaxAddCategoryMethod:(objc_methodRef)arg1 toClass:(Class)arg2 isClass:(BOOL)arg3 ;
+(Class)imaxTargetClass;
+(void)imaxAddSafeCategoryDependenciesToCollection:(id)arg1 ;
@end

