/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <IMCommonCore/IMCommonCore-Structs.h>
@class CAMediaTimingFunction, IMAnimationFloatFunction;

@interface IMAnimationSizeFunction : NSObject {

	CAMediaTimingFunction* _timingFunction;
	double _speed;
	IMAnimationFloatFunction* _widthFunction;
	IMAnimationFloatFunction* _heightFunction;
	CGSize _startValue;
	CGSize _endValue;

}

@property (nonatomic,retain) IMAnimationFloatFunction * widthFunction;               //@synthesize widthFunction=_widthFunction - In the implementation block
@property (nonatomic,retain) IMAnimationFloatFunction * heightFunction;              //@synthesize heightFunction=_heightFunction - In the implementation block
@property (nonatomic,retain) CAMediaTimingFunction * timingFunction;                 //@synthesize timingFunction=_timingFunction - In the implementation block
@property (assign,nonatomic) CGSize startValue;                                      //@synthesize startValue=_startValue - In the implementation block
@property (assign,nonatomic) CGSize endValue;                                        //@synthesize endValue=_endValue - In the implementation block
@property (assign,nonatomic) double speed;                                           //@synthesize speed=_speed - In the implementation block
-(CGSize)solveForTime:(double)arg1 ;
-(void)_reloadFunctions;
-(IMAnimationFloatFunction *)widthFunction;
-(IMAnimationFloatFunction *)heightFunction;
-(void)setWidthFunction:(IMAnimationFloatFunction *)arg1 ;
-(void)setHeightFunction:(IMAnimationFloatFunction *)arg1 ;
-(id)initWithTimingFunction:(id)arg1 startRect:(CGSize)arg2 endRect:(CGSize)arg3 speed:(double)arg4 ;
-(void)setSpeed:(double)arg1 ;
-(CAMediaTimingFunction *)timingFunction;
-(double)speed;
-(void)setTimingFunction:(CAMediaTimingFunction *)arg1 ;
-(void)setStartValue:(CGSize)arg1 ;
-(void)setEndValue:(CGSize)arg1 ;
-(CGSize)endValue;
-(CGSize)startValue;
@end

