/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:24 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <IMCommonCore/IMBlockActivityItemProvider.h>

@interface IMBlockActivityItemPlusThumbnailProvider : IMBlockActivityItemProvider {

	/*^block*/id _thumbnailResolutionBlock;

}

@property (nonatomic,copy) id thumbnailResolutionBlock;              //@synthesize thumbnailResolutionBlock=_thumbnailResolutionBlock - In the implementation block
-(id)initWithUTI:(id)arg1 resolutionBlock:(/*^block*/id)arg2 thumbnailResolutionBlock:(/*^block*/id)arg3 ;
-(id)thumbnailResolutionBlock;
-(void)setThumbnailResolutionBlock:(id)arg1 ;
-(id)activityViewController:(id)arg1 thumbnailImageForActivityType:(id)arg2 suggestedSize:(CGSize)arg3 ;
@end

