/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:24 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <IMCommonCore/IMCommonCore-Structs.h>
@class IMMemoryCache, NSString, NSObject, IMPersistentCache;

@interface IMImageCache : NSObject {

	IMMemoryCache* _memoryCache;
	NSString* _persistentCachePath;
	NSObject*<OS_dispatch_queue> _downloadQueue;
	NSString* _defaultType;
	NSObject*<OS_dispatch_queue> _persistenceQueue;
	IMPersistentCache* _persistentCache;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> persistenceQueue;              //@synthesize persistenceQueue=_persistenceQueue - In the implementation block
@property (retain) IMPersistentCache * persistentCache;                                  //@synthesize persistentCache=_persistentCache - In the implementation block
@property (nonatomic,copy) NSString * defaultType;                                       //@synthesize defaultType=_defaultType - In the implementation block
+(id)defaultCache;
-(id)initWithIdentifier:(id)arg1 basePath:(id)arg2 memorySize:(long long)arg3 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 persist:(BOOL)arg4 ;
-(IMPersistentCache *)persistentCache;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 persist:(BOOL)arg4 properties:(id)arg5 ;
-(void)flushPersistentCache;
-(id)genericKeyWithBaseKey:(id)arg1 ;
-(void)removeImageForKey:(id)arg1 synchronous:(BOOL)arg2 ;
-(id)_fetchImageForKey:(id)arg1 ;
-(id)keyForSize:(CGSize)arg1 withBaseKey:(id)arg2 ;
-(void)imageForKey:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 options:(int)arg5 ;
-(void)addImageFromURL:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 ;
-(void)addImageFromURL:(id)arg1 key:(id)arg2 size:(CGSize)arg3 completionBlock:(/*^block*/id)arg4 queue:(id)arg5 ;
-(BOOL)hasImageForKey:(id)arg1 ;
-(void)_histogramForImage:(id)arg1 result:(unsigned*)arg2 size:(unsigned)arg3 ;
-(id)initWithIdentifier:(id)arg1 memorySize:(long long)arg2 ;
-(void)removeGenericImageForKey:(id)arg1 ;
-(void)removeImageWithRootKey:(id)arg1 ;
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 ;
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 resizeOptions:(int)arg3 ;
-(void)imageForKey:(id)arg1 completionBlock:(/*^block*/id)arg2 queue:(id)arg3 ;
-(void)imageForKey:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 ;
-(void)addImageFromURL:(id)arg1 completionBlock:(/*^block*/id)arg2 queue:(id)arg3 ;
-(unsigned long long)imageDataSizeForKey:(id)arg1 ;
-(id)imageWithString:(id)arg1 size:(CGSize)arg2 save:(BOOL)arg3 ;
-(double)compareImage:(id)arg1 withImage:(id)arg2 ;
-(BOOL)hasImageForKey:(id)arg1 withSize:(CGSize)arg2 ;
-(void)getImageMetadataForKey:(id)arg1 size:(CGSize*)arg2 scale:(double*)arg3 ;
-(id)keyForSize:(CGSize)arg1 withBaseKey:(id)arg2 suffix:(id)arg3 ;
-(NSString *)defaultType;
-(void)setDefaultType:(NSString *)arg1 ;
-(void)setPersistenceQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setPersistentCache:(IMPersistentCache *)arg1 ;
-(void)dealloc;
-(void)removeImageForKey:(id)arg1 ;
-(id)imageForKey:(id)arg1 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 ;
-(void)flushMemoryCache;
-(void)flushAllCaches;
-(NSObject*<OS_dispatch_queue>)persistenceQueue;
@end

