/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSMutableDictionary, IMPlistConfigurationEnvironment;

@interface IMPlistConfiguration : NSObject <NSCopying> {

	NSArray* _plist;
	NSMutableDictionary* _cache;
	IMPlistConfigurationEnvironment* _enviroment;

}

@property (nonatomic,retain) IMPlistConfigurationEnvironment * enviroment;              //@synthesize enviroment=_enviroment - In the implementation block
-(void)setEnviroment:(IMPlistConfigurationEnvironment *)arg1 ;
-(IMPlistConfigurationEnvironment *)enviroment;
-(void)loadConfiguration:(id)arg1 ;
-(CGSize)sizeForKey:(id)arg1 ;
-(CGPoint)pointForKey:(id)arg1 ;
-(UIEdgeInsets)edgeInsetsForKey:(id)arg1 ;
-(id)init;
-(id)valueForKey:(id)arg1 ;
-(void)invalidate;
-(double)floatForKey:(id)arg1 ;
-(double)boolForKey:(id)arg1 ;
-(id)stringForKey:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)integerForKey:(id)arg1 ;
-(id)valueForUndefinedKey:(id)arg1 ;
-(id)initWithConfiguration:(id)arg1 ;
-(void)loadConfigurationFromURL:(id)arg1 ;
-(CGRect)rectForKey:(id)arg1 ;
@end

