/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:25 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSURL;

@interface IMUbiquitousPersistentStoreLoader : NSObject {

	NSString* _identifier;
	NSURL* _persistentStoreURL;
	NSString* _storeName;
	NSString* _managedObjectModelName;
	BOOL _isUbiquitous;
	NSString* _ubiquitousStoreIdentifier;
	NSString* _ubiquitousContentName;
	NSString* _ubiquitousPeerIDOverride;

}

@property (nonatomic,readonly) NSURL * storeURL; 
@property (nonatomic,retain) NSURL * persistentStoreURL;                        //@synthesize persistentStoreURL=_persistentStoreURL - In the implementation block
@property (nonatomic,readonly) NSString * identifier;                           //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) NSString * storeName;                              //@synthesize storeName=_storeName - In the implementation block
@property (nonatomic,retain) NSString * managedObjectModelName;                 //@synthesize managedObjectModelName=_managedObjectModelName - In the implementation block
@property (assign,nonatomic) BOOL isUbiquitous;                                 //@synthesize isUbiquitous=_isUbiquitous - In the implementation block
@property (nonatomic,retain) NSString * ubiquitousStoreIdentifier;              //@synthesize ubiquitousStoreIdentifier=_ubiquitousStoreIdentifier - In the implementation block
@property (nonatomic,retain) NSString * ubiquitousContentName;                  //@synthesize ubiquitousContentName=_ubiquitousContentName - In the implementation block
@property (nonatomic,retain) NSString * ubiquitousPeerIDOverride;               //@synthesize ubiquitousPeerIDOverride=_ubiquitousPeerIDOverride - In the implementation block
-(NSString *)managedObjectModelName;
-(id)ubiquitousContainerURL;
-(NSString *)ubiquitousPeerIDOverride;
-(id)addPersistentStoreToPersistentStoreCoordinator:(id)arg1 includeUbiquitousOptions:(BOOL)arg2 ;
-(BOOL)storeFileExists;
-(NSString *)ubiquitousContentName;
-(void)setManagedObjectModelName:(NSString *)arg1 ;
-(NSString *)ubiquitousStoreIdentifier;
-(id)addPersistentStoreToPersistentStoreCoordinator:(id)arg1 withType:(id)arg2 configuration:(id)arg3 URL:(id)arg4 options:(id)arg5 ;
-(void)setPersistentStoreURL:(NSURL *)arg1 ;
-(void)deletePersistentStore;
-(void)setUbiquitousStoreIdentifier:(NSString *)arg1 ;
-(void)setUbiquitousContentName:(NSString *)arg1 ;
-(void)setUbiquitousPeerIDOverride:(NSString *)arg1 ;
-(BOOL)isUbiquitous;
-(NSString *)storeName;
-(void)setStoreName:(NSString *)arg1 ;
-(id)init;
-(NSString *)identifier;
-(id)initWithIdentifier:(id)arg1 ;
-(NSURL *)storeURL;
-(void)setIsUbiquitous:(BOOL)arg1 ;
-(NSURL *)persistentStoreURL;
-(id)initWithPersistentStoreURL:(id)arg1 ;
@end

