/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:49 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImage, UIColor, NSString;


@protocol ACMExternalUIControllerProtocol <ACMUIControllerProtocol>
@property (assign,nonatomic) unsigned long long signInStyle; 
@property (nonatomic,retain) UIImage * logoImage; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder; 
@property (assign,nonatomic) CGPoint widgetPosition; 
@property (nonatomic,retain) NSString * widgetAccountLabel; 
@property (nonatomic,retain) id signInButton; 
@property (nonatomic,retain) id cancelButton; 
@property (assign,nonatomic) long long widgetPasswordReturnKeyType; 
@property (assign,nonatomic) BOOL shouldAuthenticateOnUserInput; 
@property (assign,nonatomic) NSString * password; 
@required
-(void)setBackgroundColor:(id)arg1;
-(UIColor *)backgroundColor;
-(void)setCancelButton:(id)arg1;
-(id)cancelButton;
-(id)signInButton;
-(void)setLogoImage:(id)arg1;
-(UIImage *)logoImage;
-(void)setWidgetPosition:(CGPoint)arg1;
-(void)setWidgetAccountLabel:(id)arg1;
-(void)setWidgetPasswordReturnKeyType:(long long)arg1;
-(void)setSignInButton:(id)arg1;
-(void)setShouldAuthenticateOnUserInput:(BOOL)arg1;
-(void)setAccountNameFieldPlaceholder:(id)arg1;
-(void)setSignInStyle:(unsigned long long)arg1;
-(unsigned long long)signInStyle;
-(NSString *)accountNameFieldPlaceholder;
-(CGPoint)widgetPosition;
-(long long)widgetPasswordReturnKeyType;
-(NSString *)widgetAccountLabel;
-(BOOL)shouldAuthenticateOnUserInput;
-(NSString *)password;
-(void)setPassword:(id)arg1;

@end

