/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:49 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMAppleConnectImplComponents.h>

@interface ACMExternalAppleConnectImplComponents : ACMAppleConnectImplComponents
+(id)components;
-(id)preferences;
-(id)createHandlerWithClass:(Class)arg1 context:(id)arg2 ;
-(id)twoSVController;
-(id)uiController;
-(id)createAppleConnectImpl;
-(id)createAppleConnectImplWithMasterObject:(id)arg1 ;
-(BOOL)uiControllerLoaded;
-(void)unloadUIController;
-(id)createAuthenticationRequest;
@end

