/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:36:50 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImage, UIColor, NSString;


@protocol ACMSignInDialogSimpleProtocol <ACMSignInDialogProtocol>
@property (nonatomic,retain) UIImage * logo; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder; 
@required
-(void)setBackgroundColor:(id)arg1;
-(UIColor *)backgroundColor;
-(UIImage *)logo;
-(void)setLogo:(id)arg1;
-(void)setAccountNameFieldPlaceholder:(id)arg1;
-(NSString *)accountNameFieldPlaceholder;

@end

