/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:13 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/News.app/Frameworks/SilexJSONObject.framework/SilexJSONObject
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_semaphore;
#import <SilexJSONObject/SilexJSONObject-Structs.h>
@class NSDictionary, NSObject, NSString, NSMutableDictionary;

@interface SXJSONObject : NSObject {

	NSDictionary* _jsonDictionary;
	NSObject*<OS_dispatch_semaphore> _semaphore;
	NSString* _specificationVersion;
	NSMutableDictionary* _objectStorage;
	id _backingObject;

}

@property (nonatomic,retain) NSDictionary * jsonDictionary;                             //@synthesize jsonDictionary=_jsonDictionary - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_semaphore> semaphore;              //@synthesize semaphore=_semaphore - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * objectStorage;                       //@synthesize objectStorage=_objectStorage - In the implementation block
@property (nonatomic,readonly) NSString * specificationVersion;                         //@synthesize specificationVersion=_specificationVersion - In the implementation block
@property (nonatomic,retain) id backingObject;                                          //@synthesize backingObject=_backingObject - In the implementation block
+(/*^block*/id)objectValueClassBlockForPropertyWithName:(id)arg1 ;
+(/*^block*/id)valueClassBlockForPropertyWithName:(id)arg1 ;
+(/*^block*/id)purgeClassBlockForPropertyWithName:(id)arg1 ;
+(void)initializeJSONObject;
+(void)initializeObject;
+(id)propertyDefinitions;
+(Class)classOverrideAtInitialization:(Class)arg1 type:(id)arg2 ;
+(id)propertyHashTable;
+(id)jsonPropertyNameForObjCPropertyName:(id)arg1 ;
+(void)initialize;
-(NSString *)specificationVersion;
-(id)initWithJSONObject:(id)arg1 andVersion:(id)arg2 ;
-(void)setBackingObject:(id)arg1 forPropertiesOfClass:(Class)arg2 ;
-(void)setBackingObject:(id)arg1 ;
-(NSDictionary *)jsonDictionary;
-(id)backingObject;
-(NSMutableDictionary *)objectStorage;
-(id)valueForLookupKey:(id)arg1 ;
-(id)initWithBackingObject:(id)arg1 andVersion:(id)arg2 ;
-(id)initWithJSONData:(id)arg1 andVersion:(id)arg2 ;
-(id)jsonData;
-(void)storeObject:(id)arg1 forLookupKey:(id)arg2 ;
-(id)objectForLookupKey:(id)arg1 ;
-(void)storeValue:(id)arg1 forLookupKey:(id)arg2 ;
-(BOOL)hasJSONStore;
-(void)setJsonDictionary:(NSDictionary *)arg1 ;
-(void)setObjectStorage:(NSMutableDictionary *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSObject*<OS_dispatch_semaphore>)semaphore;
@end

