/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
@interface RTArchiver : NSObject {

	archiveRef _archive;
	BOOL _valid;

}

@property (assign,nonatomic) BOOL valid;              //@synthesize valid=_valid - In the implementation block
-(void)dealloc;
-(BOOL)valid;
-(void)setValid:(BOOL)arg1 ;
-(void)closeArchive;
-(void)addPathToArchive:(id)arg1 ;
-(void)addFileToArchive:(id)arg1 ;
-(id)initWithOutputURL:(id)arg1 compress:(BOOL)arg2 ;
@end

