/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTXPCListener.h>
#import <libobjc.A.dylib/RTClientListenerProtocol.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@class NSMutableDictionary, NSString;

@interface RTClientListener : RTXPCListener <RTClientListenerProtocol, NSXPCListenerDelegate> {

	NSMutableDictionary* _persistedClients;

}

@property (nonatomic,retain) NSMutableDictionary * persistedClients;              //@synthesize persistedClients=_persistedClients - In the implementation block
@property (nonatomic,readonly) NSString * persistedClientsPath; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)_setup;
-(id)handleClientConnection:(id)arg1 ;
-(void)handleDisconnectionForDaemonClient:(id)arg1 ;
-(void)saveDaemonClient:(id)arg1 ;
-(id)handleRestorationForDaemonClient:(id)arg1 ;
-(NSString *)persistedClientsPath;
-(void)setPersistedClients:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)persistedClients;
@end

