/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTDataProviderEvent.h>

@class NSMutableArray;

@interface RTDataProviderDuet : RTDataProviderEvent {

	NSMutableArray* _duetHelpers;

}

@property (nonatomic,retain) NSMutableArray * duetHelpers;              //@synthesize duetHelpers=_duetHelpers - In the implementation block
-(void)shutdown;
-(void)_purge;
-(id)initWithName:(id)arg1 purgeManager:(id)arg2 ;
-(id)duetHelperForDuetEventStream:(long long)arg1 ;
-(id)supportedEventStreams;
-(void)_destroyDuetHelpers;
-(void)_createDuetHelpersWithEventStreamTypes:(id)arg1 ;
-(NSMutableArray *)duetHelpers;
-(void)setDuetHelpers:(NSMutableArray *)arg1 ;
@end

