/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTDaemonClientRegistrar.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/RTDaemonClientRegistrarProtocol.h>

@protocol RTDaemonClientRegistrarApplicationPredictionProtocol, OS_dispatch_queue;
@class NSPredicate, RTInvocationDispatcher, RTPredictedApplicationManager, NSObject, NSString;

@interface RTDaemonClientRegistrarApplicationPrediction : RTDaemonClientRegistrar <NSSecureCoding, RTDaemonClientRegistrarProtocol> {

	BOOL _registered;
	NSPredicate* _applicationPredicate;
	id<RTDaemonClientRegistrarApplicationPredictionProtocol> _delegate;
	RTInvocationDispatcher* _dispatcher;
	RTPredictedApplicationManager* _predictedApplicationManager;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) RTInvocationDispatcher * dispatcher;                                                   //@synthesize dispatcher=_dispatcher - In the implementation block
@property (nonatomic,retain) RTPredictedApplicationManager * predictedApplicationManager;                           //@synthesize predictedApplicationManager=_predictedApplicationManager - In the implementation block
@property (nonatomic,retain) NSPredicate * applicationPredicate;                                                    //@synthesize applicationPredicate=_applicationPredicate - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                                    //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic,__weak) id<RTDaemonClientRegistrarApplicationPredictionProtocol> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)supportsSecureCoding;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setDelegate:(id<RTDaemonClientRegistrarApplicationPredictionProtocol>)arg1 ;
-(id<RTDaemonClientRegistrarApplicationPredictionProtocol>)delegate;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(RTInvocationDispatcher *)dispatcher;
-(BOOL)invocationsPending;
-(void)setDispatcher:(RTInvocationDispatcher *)arg1 ;
-(long long)countOfPendingInvocations;
-(id)initWithPredictedApplicationManager:(id)arg1 queue:(id)arg2 ;
-(void)startMonitoringForPredictedApplicationsUsingPredicate:(id)arg1 ;
-(void)stopMonitoringForPredictedApplications;
-(void)addPendingApplicationPredictionBlock:(/*^block*/id)arg1 failBlock:(/*^block*/id)arg2 description:(id)arg3 ;
-(NSPredicate *)applicationPredicate;
-(BOOL)registered;
-(void)setApplicationPredicate:(NSPredicate *)arg1 ;
-(RTPredictedApplicationManager *)predictedApplicationManager;
-(void)onPredictedApplicationNotification:(id)arg1 ;
-(BOOL)evaluatePredicateKeyPath;
-(void)setPredictedApplicationManager:(RTPredictedApplicationManager *)arg1 ;
@end

