/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSArray;

@interface RTDefaultsManagerNotificationDefaultsChanged : RTNotification {

	NSArray* _updatedKeys;

}

@property (nonatomic,retain) NSArray * updatedKeys;              //@synthesize updatedKeys=_updatedKeys - In the implementation block
-(id)initWithUpdatedKeys:(id)arg1 ;
-(NSArray *)updatedKeys;
-(void)setUpdatedKeys:(NSArray *)arg1 ;
@end

