/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>
#import <libobjc.A.dylib/RTStateModelDelegate.h>
#import <libobjc.A.dylib/RTNextPredictedLocationsOfInterestCacheDelegate.h>
#import <libobjc.A.dylib/RTSyncServiceClientProtocol.h>

@protocol OS_dispatch_source;
@class RTStateModel, NSMutableArray, RTNextPredictedLocationsOfInterestCache, NSDate, NSObject, NSArray, RTSyncService, RTTaskScheduler, NSUUID, NSString;

@interface RTDeviceLocationPredictor : RTNotifier <RTStateModelDelegate, RTNextPredictedLocationsOfInterestCacheDelegate, RTSyncServiceClientProtocol> {

	BOOL _encryptedDataAvailabilityNotificationNeeded;
	BOOL _monitorNextPredictedLocationsOfInterest;
	BOOL _pendingNextPredictedLocationsOfInterestRequest;
	RTStateModel* _stateModel;
	NSMutableArray* _pendingStateModelInvocations;
	long long _encryptedDataAvailability;
	RTNextPredictedLocationsOfInterestCache* _nextPredictedLocationsOfInterestCache;
	NSDate* _lastNextPredictedLocationsOfInterestDate;
	NSObject*<OS_dispatch_source> _nextPredictedLocationsOfInterestPollLocationTimer;
	NSArray* _nextPredictedLocationsOfInterest;
	double _nextPredictedLocationsOfInterestProcessInterval;
	double _nextPredictedLocationsOfInterestPollLocationInterval;
	RTSyncService* _syncService;
	NSMutableArray* _evalPredictedLocationsOfInterest;
	RTTaskScheduler* _taskScheduler;
	NSUUID* _routineModelSyncTaskIdentifier;

}

@property (nonatomic,retain) RTStateModel * stateModel;                                                                    //@synthesize stateModel=_stateModel - In the implementation block
@property (nonatomic,retain) NSMutableArray * pendingStateModelInvocations;                                                //@synthesize pendingStateModelInvocations=_pendingStateModelInvocations - In the implementation block
@property (assign,nonatomic) long long encryptedDataAvailability;                                                          //@synthesize encryptedDataAvailability=_encryptedDataAvailability - In the implementation block
@property (nonatomic,retain) RTNextPredictedLocationsOfInterestCache * nextPredictedLocationsOfInterestCache;              //@synthesize nextPredictedLocationsOfInterestCache=_nextPredictedLocationsOfInterestCache - In the implementation block
@property (assign,nonatomic) BOOL encryptedDataAvailabilityNotificationNeeded;                                             //@synthesize encryptedDataAvailabilityNotificationNeeded=_encryptedDataAvailabilityNotificationNeeded - In the implementation block
@property (assign,nonatomic) BOOL monitorNextPredictedLocationsOfInterest;                                                 //@synthesize monitorNextPredictedLocationsOfInterest=_monitorNextPredictedLocationsOfInterest - In the implementation block
@property (nonatomic,retain) NSDate * lastNextPredictedLocationsOfInterestDate;                                            //@synthesize lastNextPredictedLocationsOfInterestDate=_lastNextPredictedLocationsOfInterestDate - In the implementation block
@property (assign,nonatomic) BOOL pendingNextPredictedLocationsOfInterestRequest;                                          //@synthesize pendingNextPredictedLocationsOfInterestRequest=_pendingNextPredictedLocationsOfInterestRequest - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> nextPredictedLocationsOfInterestPollLocationTimer;              //@synthesize nextPredictedLocationsOfInterestPollLocationTimer=_nextPredictedLocationsOfInterestPollLocationTimer - In the implementation block
@property (nonatomic,retain) NSArray * nextPredictedLocationsOfInterest;                                                   //@synthesize nextPredictedLocationsOfInterest=_nextPredictedLocationsOfInterest - In the implementation block
@property (assign,nonatomic) double nextPredictedLocationsOfInterestProcessInterval;                                       //@synthesize nextPredictedLocationsOfInterestProcessInterval=_nextPredictedLocationsOfInterestProcessInterval - In the implementation block
@property (assign,nonatomic) double nextPredictedLocationsOfInterestPollLocationInterval;                                  //@synthesize nextPredictedLocationsOfInterestPollLocationInterval=_nextPredictedLocationsOfInterestPollLocationInterval - In the implementation block
@property (nonatomic,retain) RTSyncService * syncService;                                                                  //@synthesize syncService=_syncService - In the implementation block
@property (nonatomic,retain) NSMutableArray * evalPredictedLocationsOfInterest;                                            //@synthesize evalPredictedLocationsOfInterest=_evalPredictedLocationsOfInterest - In the implementation block
@property (nonatomic,retain) RTTaskScheduler * taskScheduler;                                                              //@synthesize taskScheduler=_taskScheduler - In the implementation block
@property (nonatomic,retain) NSUUID * routineModelSyncTaskIdentifier;                                                      //@synthesize routineModelSyncTaskIdentifier=_routineModelSyncTaskIdentifier - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)clear;
-(void)purge;
-(void)fetchPredictedLocationsOfInterestOnDate:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)_setup;
-(void)fetchLocationOfInterestAtCachedLocationWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLocationOfInterestAtCurrentLocationWithHandler:(/*^block*/id)arg1 ;
-(void)_purge;
-(void)setup;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)fetchLocationOfInterestWithIdentifier:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)fetchLocationsOfInterestOfType:(long long)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)fetchAllLocationsOfInterestWithHandler:(/*^block*/id)arg1 ;
-(void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(/*^block*/id)arg4 ;
-(void)fetchRoutineModeFromLocation:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(BOOL)monitorNextPredictedLocationsOfInterest;
-(NSArray *)nextPredictedLocationsOfInterest;
-(void)fetchLocationOfInterestAtLocation:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)fetchPredictedExitDatesFromLocation:(id)arg1 onDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)fetchPredictedLocationsOfInterestBetweenStartDate:(id)arg1 endDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)setMonitorNextPredictedLocationsOfInterest:(BOOL)arg1 ;
-(void)addLocationOfInterestOfType:(long long)arg1 mapItem:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)updateLocationOfInterestWithIdentifier:(id)arg1 type:(long long)arg2 mapItem:(id)arg3 customLabel:(id)arg4 handler:(/*^block*/id)arg5 ;
-(void)updateLocationOfInterestWithIdentifier:(id)arg1 mapItem:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)updateLocationOfInterestWithIdentifier:(id)arg1 type:(long long)arg2 handler:(/*^block*/id)arg3 ;
-(void)updateLocationOfInterestWithIdentifier:(id)arg1 customLabel:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)forceSequentialClusterIdentification:(/*^block*/id)arg1 ;
-(void)syncRoutineStateModelFromCompanionToGizmo:(/*^block*/id)arg1 ;
-(void)injectLocationOfInterest:(id)arg1 ;
-(void)removeLocationOfInterest:(id)arg1 ;
-(void)injectVisit:(id)arg1 locationOfInterest:(id)arg2 ;
-(void)removeVisit:(id)arg1 locationOfInterest:(id)arg2 ;
-(void)onPurgeNotification:(id)arg1 ;
-(long long)encryptedDataAvailability;
-(void)setEncryptedDataAvailability:(long long)arg1 ;
-(void)onLocationNotification:(id)arg1 ;
-(void)_fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(/*^block*/id)arg4 ;
-(void)syncService:(id)arg1 didReceiveMessage:(id)arg2 ;
-(void)forceContactStoreMeContactDidChange;
-(void)_fetchPredictedLocationsOfInterestBetweenStartDate:(id)arg1 endDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)fetchLocationsOfInterestWithinStartDate:(id)arg1 endDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)setNextPredictedLocationsOfInterest:(NSArray *)arg1 ;
-(RTSyncService *)syncService;
-(void)initStateModel:(id)arg1 ;
-(void)sequentialClusterIdentification;
-(void)scheduleSyncTaskWithHandler:(/*^block*/id)arg1 ;
-(void)onPairedDeviceUpdate:(id)arg1 ;
-(void)_updateEvalPredictedLocationsOfInterest;
-(void)_onLocations:(id)arg1 ;
-(void)onContactsManagerNotification:(id)arg1 ;
-(void)_scheduleSyncTaskWithHandler:(/*^block*/id)arg1 ;
-(NSUUID *)routineModelSyncTaskIdentifier;
-(RTTaskScheduler *)taskScheduler;
-(void)setRoutineModelSyncTaskIdentifier:(NSUUID *)arg1 ;
-(RTStateModel *)stateModel;
-(void)setStateModel:(RTStateModel *)arg1 ;
-(void)onLocationsOfInterestUpdated;
-(void)_clear;
-(NSMutableArray *)pendingStateModelInvocations;
-(RTNextPredictedLocationsOfInterestCache *)nextPredictedLocationsOfInterestCache;
-(void)_sequentialClusterIdentification;
-(void)logStateModelAvailabilityMetricWithAvailability:(long long)arg1 ;
-(NSMutableArray *)evalPredictedLocationsOfInterest;
-(void)_sequentialClusterIdentificationWithHandler:(/*^block*/id)arg1 ;
-(void)_onContactStoreMeContactDidChange;
-(void)_fetchLocationOfInterestAtLocation:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)shouldMonitorNextPredictedLocationsOfInterest;
-(void)sendModelToEligibleDevices:(/*^block*/id)arg1 ;
-(void)setEncryptedDataAvailabilityNotificationNeeded:(BOOL)arg1 ;
-(void)onDataProtectionNotification:(id)arg1 ;
-(void)updateEncryptedDataAvailabilityNotificationNeeded;
-(void)_fetchPredictedExitDatesFromLocation:(id)arg1 onDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(NSObject*<OS_dispatch_source>)nextPredictedLocationsOfInterestPollLocationTimer;
-(double)nextPredictedLocationsOfInterestPollLocationInterval;
-(void)setPendingNextPredictedLocationsOfInterestRequest:(BOOL)arg1 ;
-(void)setLastNextPredictedLocationsOfInterestDate:(NSDate *)arg1 ;
-(void)_updateNextPredictedLocationsOfInterestWithLocations:(id)arg1 ;
-(BOOL)pendingNextPredictedLocationsOfInterestRequest;
-(NSDate *)lastNextPredictedLocationsOfInterestDate;
-(double)nextPredictedLocationsOfInterestProcessInterval;
-(void)_postNextPredictedLocationsOfInterest:(id)arg1 ;
-(void)setEvalPredictedLocationsOfInterest:(NSMutableArray *)arg1 ;
-(void)onCacheEnabledDidChange:(BOOL)arg1 ;
-(void)setPendingStateModelInvocations:(NSMutableArray *)arg1 ;
-(void)setNextPredictedLocationsOfInterestCache:(RTNextPredictedLocationsOfInterestCache *)arg1 ;
-(BOOL)encryptedDataAvailabilityNotificationNeeded;
-(void)setNextPredictedLocationsOfInterestPollLocationTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)setNextPredictedLocationsOfInterestProcessInterval:(double)arg1 ;
-(void)setNextPredictedLocationsOfInterestPollLocationInterval:(double)arg1 ;
-(void)setSyncService:(RTSyncService *)arg1 ;
-(void)setTaskScheduler:(RTTaskScheduler *)arg1 ;
@end

