/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSDate, NSObject;

@interface RTFeatureExtractor : NSObject {

	NSDate* _lastExtractionDate;
	BOOL _collectingData;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) BOOL collectingData;                             //@synthesize collectingData=_collectingData - In the implementation block
@property (nonatomic,retain) NSDate * lastExtractionDate; 
+(BOOL)enabled;
+(id)sharedInstance;
+(id)lastExtractionDate;
+(void)setLastExtractionDate:(id)arg1 ;
-(id)init;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)shutdown;
-(void)_register;
-(void)setup;
-(void)onWiFiManagerNotificationScanResults:(id)arg1 ;
-(void)onWiFiManagerNotificationPowerStatusChanged:(id)arg1 ;
-(void)_unregister;
-(void)onWiFiManagerNotificationLinkStatusChanged:(id)arg1 ;
-(void)onWalletManagerPassUsedNotification:(id)arg1 ;
-(void)onWalletManagerPaymentUsedNotification:(id)arg1 ;
-(void)onLocationsOfInterestUpdatedNotification:(id)arg1 ;
-(NSDate *)lastExtractionDate;
-(void)setLastExtractionDate:(NSDate *)arg1 ;
-(void)_collectData;
-(BOOL)collectingData;
-(void)setCollectingData:(BOOL)arg1 ;
-(void)_collectMotionDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectEventKitDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectContactsDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectMapsSupportDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectAppLaunchDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectCoreRecentsDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectCallHistoryFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_collectUserActivityLocationDataFromDate:(id)arg1 toDate:(id)arg2 usingGroup:(id)arg3 ;
-(void)_dataCollectionFinished:(id)arg1 ;
@end

