/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTLaunchServices : NSObject
+(id)createProcessAssertionForPid:(int)arg1 ;
+(void)launchClientWithBundleIdentifier:(id)arg1 restorationIdentifier:(id)arg2 options:(id)arg3 handler:(/*^block*/id)arg4 ;
+(BOOL)canOpenApplication:(id)arg1 ;
@end

