/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSObject, RTPersistenceManager, NSMutableArray, NSManagedObjectContext;

@interface RTLocationStore : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_source> _timer;
	RTPersistenceManager* _persistenceManager;
	unsigned long long _bufferCapacity;
	NSMutableArray* _buffer;
	NSManagedObjectContext* _context;
	BOOL _requestingContext;

}
+(BOOL)enabled;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)_setup;
-(void)shutdown;
-(void)fetchLocationsFromDate:(id)arg1 toDate:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)storeLocations:(id)arg1 ;
-(id)initWithPersistenceManager:(id)arg1 ;
-(void)_requestContext;
-(void)_setupTimer;
-(id)_persistLocationsAndOverflowLocations:(id)arg1 ;
-(void)_teardownTimer;
-(void)_bufferLocation:(id)arg1 ;
-(void)_bufferLocations:(id)arg1 ;
-(void)_getManagedObjectContext:(/*^block*/id)arg1 ;
-(id)_purgeLocationsPredating:(id)arg1 context:(id)arg2 ;
-(void)storeLocation:(id)arg1 ;
-(void)purgeLocationsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

