/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSDictionary;

@interface RTPredictionExpertDataSource : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSDictionary* _dataProviders;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (nonatomic,readonly) NSDictionary * dataProviders;                    //@synthesize dataProviders=_dataProviders - In the implementation block
-(void)reset;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSDictionary *)dataProviders;
-(id)dataProviderForName:(id)arg1 ;
-(id)initWithDataProviders:(id)arg1 ;
-(void)prefetch:(/*^block*/id)arg1 ;
@end

