/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertFeatureAddonMO.h>

@class NSString;

@interface RTPredictionExpertFeatureAddonContextMO : RTPredictionExpertFeatureAddonMO

@property (nonatomic,retain) NSString * key; 
@property (nonatomic,retain) id value; 
+(id)managedObjectWithKey:(id)arg1 value:(id)arg2 inManagedObjectContext:(id)arg3 ;
@end

