/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSMutableArray, RTInvocationDispatcher, RTPersistenceManager, RTDefaultsManager, RTAuthorizationManager, RTDataProtectionManager, RTMetricManager, RTLocationTagger, RTPredictionTableController, NSDictionary, NSDate;

@interface RTPredictionController : NSObject {

	BOOL _ready;
	BOOL _unlockedSinceBoot;
	unsigned long long _queueCount;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableArray* _expertQueues;
	NSMutableArray* _experts;
	RTInvocationDispatcher* _dispatcher;
	RTPersistenceManager* _persistenceManager;
	RTDefaultsManager* _defaultsManager;
	RTAuthorizationManager* _authorizationManager;
	RTDataProtectionManager* _dataProtectionManager;
	RTMetricManager* _metricManager;
	RTLocationTagger* _locationTagger;
	RTPredictionTableController* _predictionTable;
	unsigned long long _expertQueueMaxWidth;
	NSDictionary* _dataProviders;
	NSDate* _dateOfLastSuccessfulProcessing;
	NSDate* _dateOfLastProcessing;
	long long _encryptedDataAvailability;

}

@property (assign,nonatomic) unsigned long long queueCount;                                //@synthesize queueCount=_queueCount - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                           //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSMutableArray * expertQueues;                                //@synthesize expertQueues=_expertQueues - In the implementation block
@property (nonatomic,retain) NSMutableArray * experts;                                     //@synthesize experts=_experts - In the implementation block
@property (nonatomic,retain) RTInvocationDispatcher * dispatcher;                          //@synthesize dispatcher=_dispatcher - In the implementation block
@property (nonatomic,retain) RTPersistenceManager * persistenceManager;                    //@synthesize persistenceManager=_persistenceManager - In the implementation block
@property (nonatomic,retain) RTDefaultsManager * defaultsManager;                          //@synthesize defaultsManager=_defaultsManager - In the implementation block
@property (nonatomic,retain) RTAuthorizationManager * authorizationManager;                //@synthesize authorizationManager=_authorizationManager - In the implementation block
@property (nonatomic,retain) RTDataProtectionManager * dataProtectionManager;              //@synthesize dataProtectionManager=_dataProtectionManager - In the implementation block
@property (nonatomic,retain) RTMetricManager * metricManager;                              //@synthesize metricManager=_metricManager - In the implementation block
@property (nonatomic,retain) RTLocationTagger * locationTagger;                            //@synthesize locationTagger=_locationTagger - In the implementation block
@property (nonatomic,retain) RTPredictionTableController * predictionTable;                //@synthesize predictionTable=_predictionTable - In the implementation block
@property (assign,nonatomic) unsigned long long expertQueueMaxWidth;                       //@synthesize expertQueueMaxWidth=_expertQueueMaxWidth - In the implementation block
@property (nonatomic,retain) NSDictionary * dataProviders;                                 //@synthesize dataProviders=_dataProviders - In the implementation block
@property (assign,nonatomic) BOOL ready;                                                   //@synthesize ready=_ready - In the implementation block
@property (nonatomic,retain) NSDate * dateOfLastSuccessfulProcessing;                      //@synthesize dateOfLastSuccessfulProcessing=_dateOfLastSuccessfulProcessing - In the implementation block
@property (nonatomic,retain) NSDate * dateOfLastProcessing;                                //@synthesize dateOfLastProcessing=_dateOfLastProcessing - In the implementation block
@property (assign,nonatomic) BOOL unlockedSinceBoot;                                       //@synthesize unlockedSinceBoot=_unlockedSinceBoot - In the implementation block
@property (assign,nonatomic) long long encryptedDataAvailability;                          //@synthesize encryptedDataAvailability=_encryptedDataAvailability - In the implementation block
-(id)init;
-(void)dealloc;
-(void)invalidate;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setExperts:(NSMutableArray *)arg1 ;
-(NSMutableArray *)experts;
-(void)processData:(/*^block*/id)arg1 ;
-(RTAuthorizationManager *)authorizationManager;
-(void)setAuthorizationManager:(RTAuthorizationManager *)arg1 ;
-(void)refreshDataProvidersWithHandler:(/*^block*/id)arg1 ;
-(void)purgeDataProviders;
-(NSDictionary *)dataProviders;
-(RTMetricManager *)metricManager;
-(void)setMetricManager:(RTMetricManager *)arg1 ;
-(void)setDataProviders:(NSDictionary *)arg1 ;
-(RTInvocationDispatcher *)dispatcher;
-(BOOL)ready;
-(void)setDispatcher:(RTInvocationDispatcher *)arg1 ;
-(id)dataProviderForName:(id)arg1 ;
-(RTPersistenceManager *)persistenceManager;
-(void)setPersistenceManager:(RTPersistenceManager *)arg1 ;
-(long long)encryptedDataAvailability;
-(id)initWithExperts:(id)arg1 dataProviders:(id)arg2 defaultsManager:(id)arg3 authorizationManager:(id)arg4 persistenceManager:(id)arg5 dataProtectionManager:(id)arg6 metricManager:(id)arg7 locationTagger:(id)arg8 predictionTable:(id)arg9 ;
-(void)setDateOfLastSuccessfulProcessing:(NSDate *)arg1 ;
-(void)setDateOfLastProcessing:(NSDate *)arg1 ;
-(void)findUniqueContextsWithKey:(id)arg1 dataProvider:(id)arg2 expectedClass:(Class)arg3 handler:(/*^block*/id)arg4 ;
-(id)_requestExpertQueue;
-(RTDefaultsManager *)defaultsManager;
-(NSDate *)dateOfLastSuccessfulProcessing;
-(void)_handleErrorWhileProcessingData:(id)arg1 handler:(/*^block*/id)arg2 ;
-(RTPredictionTableController *)predictionTable;
-(void)_recursiveInvokeBatchedExpertsWithHandler:(/*^block*/id)arg1 ;
-(void)_processData:(/*^block*/id)arg1 ;
-(void)onDataProtectionChange:(id)arg1 ;
-(RTDataProtectionManager *)dataProtectionManager;
-(unsigned long long)queueCount;
-(unsigned long long)expertQueueMaxWidth;
-(NSMutableArray *)expertQueues;
-(void)setQueueCount:(unsigned long long)arg1 ;
-(void)_teardownExpertQueues;
-(void)_recursiveInvokeBatchedExpertsAtDate:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)submitMetricWithExpertMetrics:(id)arg1 ;
-(void)submitMetricWithPredictionTable:(id)arg1 lastProcessingDate:(id)arg2 currentProcessingStartDate:(id)arg3 ;
-(id)_finalizeProcessing;
-(BOOL)unlockedSinceBoot;
-(void)_handleUnlockedSinceBootNotification:(BOOL)arg1 ;
-(void)_handleEncryptedDataAvailabilityChange:(long long)arg1 ;
-(void)setEncryptedDataAvailability:(long long)arg1 ;
-(void)setUnlockedSinceBoot:(BOOL)arg1 ;
-(void)_refreshDataProvidersWithHandler:(/*^block*/id)arg1 ;
-(void)_purgeDataProviders;
-(void)setExpertQueues:(NSMutableArray *)arg1 ;
-(void)setDefaultsManager:(RTDefaultsManager *)arg1 ;
-(void)setDataProtectionManager:(RTDataProtectionManager *)arg1 ;
-(RTLocationTagger *)locationTagger;
-(void)setLocationTagger:(RTLocationTagger *)arg1 ;
-(void)setPredictionTable:(RTPredictionTableController *)arg1 ;
-(void)setExpertQueueMaxWidth:(unsigned long long)arg1 ;
-(NSDate *)dateOfLastProcessing;
-(void)setReady:(BOOL)arg1 ;
@end

