/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertFeatureAddon.h>

@interface RTPredictionExpertFeatureAddonWeekday : RTPredictionExpertFeatureAddon {

	long long _targetDays;

}

@property (nonatomic,readonly) long long targetDays;              //@synthesize targetDays=_targetDays - In the implementation block
-(id)description;
-(long long)targetDays;
-(id)initWithTargetDays:(long long)arg1 ;
-(long long)addonType;
-(id)weekdayStringFromMask:(long long)arg1 ;
@end

