/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTScenarioTrigger;

@interface RTScenarioTriggerNotification : RTNotification {

	RTScenarioTrigger* _scenarioTrigger;

}

@property (nonatomic,retain,readonly) RTScenarioTrigger * scenarioTrigger;              //@synthesize scenarioTrigger=_scenarioTrigger - In the implementation block
-(RTScenarioTrigger *)scenarioTrigger;
-(id)initWithScenarioTrigger:(id)arg1 ;
@end

