/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTTaskDependency.h>

@interface RTTaskDependencyReachability : RTTaskDependency {

	long long _reachability;

}

@property (nonatomic,readonly) long long reachability;              //@synthesize reachability=_reachability - In the implementation block
-(long long)reachability;
-(BOOL)evaluate:(id)arg1 ;
-(id)initWithReachability:(long long)arg1 ;
@end

