/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:28 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, RTPLOIETA, NSDate, RTPersistentTimer, NSMutableArray;

@interface RTTrafficConditionsManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _vehicleConnectedState;
	RTPLOIETA* _ploiEta;
	NSDate* _showTrafficConditionsDate;
	RTPersistentTimer* _showTrafficConditionsTimer;
	NSMutableArray* _trafficConditionsMetrics;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                          //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) unsigned long long vehicleConnectedState;                    //@synthesize vehicleConnectedState=_vehicleConnectedState - In the implementation block
@property (nonatomic,retain) RTPLOIETA * ploiEta;                                         //@synthesize ploiEta=_ploiEta - In the implementation block
@property (nonatomic,retain) NSDate * showTrafficConditionsDate;                          //@synthesize showTrafficConditionsDate=_showTrafficConditionsDate - In the implementation block
@property (nonatomic,retain) RTPersistentTimer * showTrafficConditionsTimer;              //@synthesize showTrafficConditionsTimer=_showTrafficConditionsTimer - In the implementation block
@property (nonatomic,retain) NSMutableArray * trafficConditionsMetrics;                   //@synthesize trafficConditionsMetrics=_trafficConditionsMetrics - In the implementation block
+(id)sharedInstance;
+(void)fetchPLOIETAFrom:(id)arg1 to:(id)arg2 withHandler:(/*^block*/id)arg3 ;
+(BOOL)mapsAuthorized;
+(void)fetchPLOIETAWithHandler:(/*^block*/id)arg1 ;
-(id)init;
-(void)dealloc;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)_setup;
-(void)submitMetric:(id)arg1 ;
-(void)onVisitManagerNotification:(id)arg1 ;
-(void)_onVisitManagerNotification:(id)arg1 ;
-(unsigned long long)vehicleConnectedState;
-(void)setVehicleConnectedState:(unsigned long long)arg1 ;
-(void)_handleVisit:(id)arg1 ;
-(RTPersistentTimer *)showTrafficConditionsTimer;
-(void)setShowTrafficConditionsTimer:(RTPersistentTimer *)arg1 ;
-(NSMutableArray *)trafficConditionsMetrics;
-(void)setTrafficConditionsMetrics:(NSMutableArray *)arg1 ;
-(NSDate *)showTrafficConditionsDate;
-(void)_clearTrafficConditions;
-(void)setShowTrafficConditionsTimer;
-(void)onMotionActivityNotification:(id)arg1 ;
-(void)_showTrafficConditions;
-(void)_updateTrafficCondtions;
-(void)setPloiEta:(RTPLOIETA *)arg1 ;
-(void)_onMotionActivityNotification:(id)arg1 ;
-(RTPLOIETA *)ploiEta;
-(void)setShowTrafficConditionsDate:(NSDate *)arg1 ;
-(void)submitMetrics;
@end

