/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTVisitMonitorDelegate, OS_dispatch_queue;
@class RTLocationManager, RTDeviceLocationPredictor, RTHintManager, RTMetricManager, RTLocationAwarenessManager, RTVisitMonitorState, NSObject;

@interface RTVisitMonitor : NSObject {

	BOOL _monitoringVisitIncidents;
	BOOL _monitoringLeechedVisitIncidents;
	BOOL _monitoringLowConfidenceVisitIncidents;
	id<RTVisitMonitorDelegate> _delegate;
	RTLocationManager* _locationManager;
	RTDeviceLocationPredictor* _deviceLocationPredictor;
	RTHintManager* _hintManager;
	RTMetricManager* _metricManager;
	RTLocationAwarenessManager* _locationAwarenessManager;
	RTVisitMonitorState* _state;
	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _engineDependentCount;

}

@property (nonatomic,retain) RTLocationManager * locationManager;                                     //@synthesize locationManager=_locationManager - In the implementation block
@property (assign,nonatomic,__weak) RTDeviceLocationPredictor * deviceLocationPredictor;              //@synthesize deviceLocationPredictor=_deviceLocationPredictor - In the implementation block
@property (nonatomic,retain) RTHintManager * hintManager;                                             //@synthesize hintManager=_hintManager - In the implementation block
@property (nonatomic,retain) RTMetricManager * metricManager;                                         //@synthesize metricManager=_metricManager - In the implementation block
@property (nonatomic,retain) RTLocationAwarenessManager * locationAwarenessManager;                   //@synthesize locationAwarenessManager=_locationAwarenessManager - In the implementation block
@property (nonatomic,retain) RTVisitMonitorState * state;                                             //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                      //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) BOOL monitoringVisitIncidents;                                           //@synthesize monitoringVisitIncidents=_monitoringVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLeechedVisitIncidents;                                    //@synthesize monitoringLeechedVisitIncidents=_monitoringLeechedVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLowConfidenceVisitIncidents;                              //@synthesize monitoringLowConfidenceVisitIncidents=_monitoringLowConfidenceVisitIncidents - In the implementation block
@property (assign,nonatomic) unsigned long long engineDependentCount;                                 //@synthesize engineDependentCount=_engineDependentCount - In the implementation block
@property (assign,nonatomic,__weak) id<RTVisitMonitorDelegate> delegate;                              //@synthesize delegate=_delegate - In the implementation block
+(double)evaluateMotionInducedDeviationFromDataPtCnt:(long long)arg1 sumLat_deg:(double)arg2 sumLat2_deg:(double)arg3 sumLon_deg:(double)arg4 sumLon2_deg:(double)arg5 ;
+(double)evalMaxUncFromMotionDevMotionInducedDev:(double)arg1 andMeasInducedDev:(double)arg2 ;
+(double)evaluateClustThresFromClustThresSlv:(double)arg1 motionInducedDev:(double)arg2 adaptionBasis:(double)arg3 adaptionSampleCnt:(long long)arg4 adaptionRate:(double)arg5 ;
+(double)convertLongitudeAtDateLineFromSum:(double)arg1 fromLongitude:(double)arg2 ;
+(double)MinStaticIntervalForSLVArrivalWithHint;
+(double)MinStaticIntervalForSLVArrival;
+(double)convertLongitudeInto180Format:(double)arg1 ;
+(double)LocationHeartbeatWhileAwake;
-(id)init;
-(void)setDelegate:(id<RTVisitMonitorDelegate>)arg1 ;
-(id<RTVisitMonitorDelegate>)delegate;
-(RTVisitMonitorState *)state;
-(void)setState:(RTVisitMonitorState *)arg1 ;
-(id)initWithQueue:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(RTLocationManager *)locationManager;
-(void)setLocationManager:(RTLocationManager *)arg1 ;
-(void)shutdown;
-(RTMetricManager *)metricManager;
-(void)setMetricManager:(RTMetricManager *)arg1 ;
-(RTDeviceLocationPredictor *)deviceLocationPredictor;
-(void)fetchLastLowConfidenceVisitIncidentWithHandler:(/*^block*/id)arg1 ;
-(void)setDeviceLocationPredictor:(RTDeviceLocationPredictor *)arg1 ;
-(id)initWithState:(id)arg1 queue:(id)arg2 ;
-(id)initWithLocationManager:(id)arg1 deviceLocationPredictor:(id)arg2 hintManager:(id)arg3 metricManager:(id)arg4 state:(id)arg5 queue:(id)arg6 ;
-(id)initWithLocationManager:(id)arg1 deviceLocationPredictor:(id)arg2 hintManager:(id)arg3 metricManager:(id)arg4 queue:(id)arg5 ;
-(id)initWithLocationManager:(id)arg1 deviceLocationPredictor:(id)arg2 hintManager:(id)arg3 metricManager:(id)arg4 state:(id)arg5 queue:(id)arg6 locationAwarenessManager:(id)arg7 ;
-(id)initWithLocationManager:(id)arg1 deviceLocationPredictor:(id)arg2 hintManager:(id)arg3 metricManager:(id)arg4 ;
-(void)considerLowConfidenceVisitIncidentExitAtLocation:(id)arg1 ;
-(void)resetForCurrentSampleAsHypothesis:(id)arg1 ;
-(id)recursiveVisitIncidentFromLocation:(id)arg1 ;
-(id)visitIncidentFromLocation:(id)arg1 ;
-(void)logHintSourceUsageWithLocation:(id)arg1 ;
-(void)_fetchVisitIncidentsFromLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)considerLowConfidenceVisitIncidentEntryAtLocation:(id)arg1 ;
-(RTHintManager *)hintManager;
-(void)resetWithTempBufferAsHypothesis;
-(void)startEngine;
-(void)stopEngine;
-(unsigned long long)engineDependentCount;
-(void)setEngineDependentCount:(unsigned long long)arg1 ;
-(void)setMonitoringVisitIncidents:(BOOL)arg1 ;
-(void)setMonitoringLeechedVisitIncidents:(BOOL)arg1 ;
-(void)setMonitoringLowConfidenceVisitIncidents:(BOOL)arg1 ;
-(void)onLeechedLocationsNotification:(id)arg1 ;
-(void)processLeechedLocations:(id)arg1 ;
-(RTLocationAwarenessManager *)locationAwarenessManager;
-(void)handleVisitIncident:(id)arg1 ;
-(void)handleLeechedVisitIncident:(id)arg1 ;
-(void)handleVisitMonitorStateChange;
-(void)fetchVisitIncidentsFromLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
-(BOOL)monitoringLowConfidenceVisitIncidents;
-(double)horizontalUncertaintyFromSampleSize:(long long)arg1 sumLat_deg:(double)arg2 sumLat2_deg:(double)arg3 sumLon_deg:(double)arg4 sumLon2_deg:(double)arg5 ;
-(void)handleLowConfidenceVisitIncident:(id)arg1 ;
-(BOOL)monitoringVisitIncidents;
-(BOOL)monitoringLeechedVisitIncidents;
-(void)fetchNumberOfSamplesForAdaptationWithHandler:(/*^block*/id)arg1 ;
-(void)startMonitoringVisitIncidents;
-(void)stopMonitoringVisitIncidents;
-(void)startMonitoringLeechedVisitIncidents;
-(void)stopMonitoringLeechedVisitIncidents;
-(void)startMonitoringLowConfidenceVisitIncidents;
-(void)stopMonitoringLowConfidenceVisitIncidents;
-(void)fetchVisitMonitorStatusWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLowConfidenceVisitMonitorStatusWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLastVisitIncidentWithHandler:(/*^block*/id)arg1 ;
-(void)fetchVisitMonitorState:(/*^block*/id)arg1 ;
-(void)setHintManager:(RTHintManager *)arg1 ;
-(void)setLocationAwarenessManager:(RTLocationAwarenessManager *)arg1 ;
@end

