/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:27 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSString, NSArray;

@interface RTWalletManagerNotificationPassUsed : RTNotification {

	NSString* _passTypeIdentifier;
	long long _source;
	NSArray* _storeIDs;

}

@property (nonatomic,readonly) NSString * passTypeIdentifier;              //@synthesize passTypeIdentifier=_passTypeIdentifier - In the implementation block
@property (nonatomic,readonly) long long source;                           //@synthesize source=_source - In the implementation block
@property (nonatomic,copy,readonly) NSArray * storeIDs;                    //@synthesize storeIDs=_storeIDs - In the implementation block
-(long long)source;
-(NSArray *)storeIDs;
-(NSString *)passTypeIdentifier;
-(id)initWithPassTypeIdentifier:(id)arg1 source:(long long)arg2 info:(id)arg3 ;
@end

