/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:37:55 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libsysdiagnose.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Libsysdiagnose : NSObject
+(void)setupConnection;
+(id)sysdiagnoseWithMetadata:(id)arg1 withError:(id*)arg2 ;
+(void)addErrorString:(id)arg1 WithCode:(id)arg2 forError:(id*)arg3 ;
+(id)createSysdiagnoseRequest:(id)arg1 ;
+(id)sendSysdiagnoseRequest:(id)arg1 withError:(id*)arg2 ;
@end

