/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:45 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libAXSafeCategoryBundle.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAXSafeCategoryBundle.dylib/libAXSafeCategoryBundle.dylib-Structs.h>
@class NSString;

@interface UIAccessibilitySafeCategory : NSObject

@property (nonatomic,copy) NSString * accessibilityIdentifier; 
+(id)_installSafeCategoryOnClassNamed:(id)arg1 isManaged:(BOOL)arg2 ;
+(id)_installLocalValidationMethodOnClassNamed:(id)arg1 ;
+(void)_addCategoryMethod:(objc_methodRef)arg1 toClass:(Class)arg2 isClass:(BOOL)arg3 ;
+(id)_installSafeCategoryOnClass:(Class)arg1 isManaged:(BOOL)arg2 ;
+(Class)safeCategoryTargetClass;
+(void)safeCategoryAddDependenciesToCollection:(id)arg1 ;
+(void)_installSafeCategoryOnClassNamed:(id)arg1 ;
+(id)safeCategoryTargetClassName;
+(id)_installSafeCategoryValidationMethod;
+(Class)safeCategoryBaseClass;
+(id)_initializeSafeCategoryFromValidationManager;
@end

