/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:16 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel, UIImageView, SVListProgressView, NSLayoutConstraint;

@interface SVFileTableViewCell : UITableViewCell {

	BOOL _enabled;
	UILabel* _nameLabel;
	UILabel* _detailLabel;
	UIImageView* _iconImageView;
	SVListProgressView* _downloadProgressView;
	long long _itemType;
	UIImageView* _badgeImageView;
	NSLayoutConstraint* _badgeViewTrailingConstraint;
	NSLayoutConstraint* _badgeViewBottomConstraint;

}

@property (assign,nonatomic,__weak) UIImageView * badgeImageView;                                  //@synthesize badgeImageView=_badgeImageView - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * badgeViewTrailingConstraint;              //@synthesize badgeViewTrailingConstraint=_badgeViewTrailingConstraint - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * badgeViewBottomConstraint;                //@synthesize badgeViewBottomConstraint=_badgeViewBottomConstraint - In the implementation block
@property (assign,nonatomic,__weak) UILabel * nameLabel;                                           //@synthesize nameLabel=_nameLabel - In the implementation block
@property (assign,nonatomic,__weak) UILabel * detailLabel;                                         //@synthesize detailLabel=_detailLabel - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * iconImageView;                                   //@synthesize iconImageView=_iconImageView - In the implementation block
@property (nonatomic,retain) SVListProgressView * downloadProgressView;                            //@synthesize downloadProgressView=_downloadProgressView - In the implementation block
@property (assign,nonatomic) BOOL enabled;                                                         //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic) long long itemType;                                                   //@synthesize itemType=_itemType - In the implementation block
-(SVListProgressView *)downloadProgressView;
-(void)setDownloadProgressViewHidden:(BOOL)arg1 animated:(BOOL)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)setBadgeImage:(id)arg1 animated:(BOOL)arg2 ;
-(void)updateBadgeViewConstraints;
-(NSLayoutConstraint *)badgeViewBottomConstraint;
-(NSLayoutConstraint *)badgeViewTrailingConstraint;
-(void)setDownloadProgressView:(SVListProgressView *)arg1 ;
-(void)setBadgeViewTrailingConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setBadgeViewBottomConstraint:(NSLayoutConstraint *)arg1 ;
-(void)layoutSubviews;
-(BOOL)enabled;
-(void)setEnabled:(BOOL)arg1 ;
-(void)awakeFromNib;
-(void)setNameLabel:(UILabel *)arg1 ;
-(UILabel *)nameLabel;
-(long long)itemType;
-(void)setItemType:(long long)arg1 ;
-(UIImageView *)badgeImageView;
-(void)setBadgeImageView:(UIImageView *)arg1 ;
-(UILabel *)detailLabel;
-(void)setDetailLabel:(UILabel *)arg1 ;
-(UIImageView *)iconImageView;
-(void)setIconImageView:(UIImageView *)arg1 ;
-(void)updateFonts;
@end

