/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:17 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIControl.h>

@protocol SVViewOptionsHeaderViewDelegate;
@class UISegmentedControl, UIButton, NSLayoutConstraint;

@interface SVViewOptionsHeaderView : UIControl {

	UISegmentedControl* _sortingOptionsSegmentedControl;
	UIButton* _listViewEnabledButton;
	id<SVViewOptionsHeaderViewDelegate> _delegate;
	NSLayoutConstraint* _segmentedControlCenterXConstraint;
	NSLayoutConstraint* _segmentedControlLeadingSpaceConstraint;

}

@property (assign,nonatomic,__weak) NSLayoutConstraint * segmentedControlCenterXConstraint;                   //@synthesize segmentedControlCenterXConstraint=_segmentedControlCenterXConstraint - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * segmentedControlLeadingSpaceConstraint;              //@synthesize segmentedControlLeadingSpaceConstraint=_segmentedControlLeadingSpaceConstraint - In the implementation block
@property (assign,nonatomic,__weak) UISegmentedControl * sortingOptionsSegmentedControl;                      //@synthesize sortingOptionsSegmentedControl=_sortingOptionsSegmentedControl - In the implementation block
@property (assign,nonatomic,__weak) UIButton * listViewEnabledButton;                                         //@synthesize listViewEnabledButton=_listViewEnabledButton - In the implementation block
@property (assign,nonatomic,__weak) id<SVViewOptionsHeaderViewDelegate> delegate;                             //@synthesize delegate=_delegate - In the implementation block
-(UISegmentedControl *)sortingOptionsSegmentedControl;
-(UIButton *)listViewEnabledButton;
-(NSLayoutConstraint *)segmentedControlLeadingSpaceConstraint;
-(NSLayoutConstraint *)segmentedControlCenterXConstraint;
-(void)toggleListView:(id)arg1 ;
-(void)sortOrderChanged:(id)arg1 ;
-(void)setSortingOptionsSegmentedControl:(UISegmentedControl *)arg1 ;
-(void)setListViewEnabledButton:(UIButton *)arg1 ;
-(void)setSegmentedControlCenterXConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setSegmentedControlLeadingSpaceConstraint:(NSLayoutConstraint *)arg1 ;
-(id)init;
-(void)setDelegate:(id<SVViewOptionsHeaderViewDelegate>)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id<SVViewOptionsHeaderViewDelegate>)delegate;
-(void)setEnabled:(BOOL)arg1 ;
-(void)setEnabled:(BOOL)arg1 animated:(BOOL)arg2 ;
@end

