/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:48 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDCoreRoutineHeroAppSuggestionInstance : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSString* _bundleId;
	int _lat;
	int _lon;
	NSString* _suggestionId;
	BOOL _installed;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasSuggestionId; 
@property (nonatomic,retain) NSString * suggestionId;                   //@synthesize suggestionId=_suggestionId - In the implementation block
@property (nonatomic,readonly) BOOL hasBundleId; 
@property (nonatomic,retain) NSString * bundleId;                       //@synthesize bundleId=_bundleId - In the implementation block
@property (assign,nonatomic) BOOL hasLat; 
@property (assign,nonatomic) int lat;                                   //@synthesize lat=_lat - In the implementation block
@property (assign,nonatomic) BOOL hasLon; 
@property (assign,nonatomic) int lon;                                   //@synthesize lon=_lon - In the implementation block
@property (assign,nonatomic) BOOL hasInstalled; 
@property (assign,nonatomic) BOOL installed;                            //@synthesize installed=_installed - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(NSString *)bundleId;
-(void)setBundleId:(NSString *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(int)lat;
-(void)setLat:(int)arg1 ;
-(void)setSuggestionId:(NSString *)arg1 ;
-(BOOL)hasSuggestionId;
-(NSString *)suggestionId;
-(BOOL)hasBundleId;
-(void)setHasLat:(BOOL)arg1 ;
-(BOOL)hasLat;
-(void)setLon:(int)arg1 ;
-(void)setHasLon:(BOOL)arg1 ;
-(BOOL)hasLon;
-(void)setInstalled:(BOOL)arg1 ;
-(void)setHasInstalled:(BOOL)arg1 ;
-(BOOL)hasInstalled;
-(int)lon;
-(BOOL)installed;
@end

