/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:50 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned approximateRecordCount : 1;
	unsigned recordsPerSecond : 1;
	unsigned timestamp : 1;
	unsigned result : 1;
} SCD_Struct_AW1;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned delayMs : 1;
	unsigned origSendConnectionType : 1;
	unsigned timedout : 1;
} SCD_Struct_AW2;

typedef struct {
	unsigned timestamp : 1;
	unsigned delayMs : 1;
} SCD_Struct_AW3;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned delayMs : 1;
} SCD_Struct_AW4;

typedef struct {
	unsigned timestamp : 1;
} SCD_Struct_AW5;

typedef struct {
	unsigned timestamp : 1;
	unsigned autoLoginType : 1;
	unsigned durationNetworkNotCaptive : 1;
	unsigned durationOnNetwork : 1;
	unsigned passiveCaptivityCorrectDetection : 1;
	unsigned passiveCaptivityIncorrectDetection : 1;
	unsigned passiveCaptivitySymptom : 1;
	unsigned result : 1;
	unsigned websheetProbeCount : 1;
	unsigned websheetScrapeResult : 1;
	unsigned autoLoginFailed : 1;
	unsigned detectedNotCaptiveHandledByCNP : 1;
	unsigned handlerCNPTriggeredLogOff : 1;
	unsigned isDetectedCaptive : 1;
	unsigned passiveCaptivityDetected : 1;
	unsigned websheetScraped : 1;
	unsigned wisprDetected : 1;
} SCD_Struct_AW6;

typedef struct {
	unsigned long long list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_AW7;

typedef struct {
	unsigned connectEnd : 1;
	unsigned connectStart : 1;
	unsigned domainLookupEnd : 1;
	unsigned domainLookupStart : 1;
	unsigned fetchStart : 1;
	unsigned isCellular : 1;
	unsigned isReused : 1;
	unsigned redirectCount : 1;
	unsigned redirectCountW3C : 1;
	unsigned redirectEnd : 1;
	unsigned redirectStart : 1;
	unsigned requestStart : 1;
	unsigned responseEnd : 1;
	unsigned responseStart : 1;
	unsigned secureConnectionStart : 1;
	unsigned timestamp : 1;
} SCD_Struct_AW8;

typedef struct {
	unsigned timestamp : 1;
	unsigned horizontalAccuracy : 1;
	unsigned locationType : 1;
	unsigned qualityIndicator : 1;
	unsigned triggerTypes : 1;
	unsigned userAssistanceRequired : 1;
} SCD_Struct_AW9;

typedef struct {
	unsigned timestamp : 1;
	unsigned assistances : 1;
	unsigned assistedParkingEvents : 1;
	unsigned duration : 1;
	unsigned engagedParkingEvents : 1;
	unsigned engagements : 1;
	unsigned locationType : 1;
	unsigned parkingEvents : 1;
	unsigned suppressedParkingEvents : 1;
} SCD_Struct_AW10;

typedef struct {
	unsigned timestamp : 1;
	unsigned dailyEvents : 1;
	unsigned eventsWithLMPLocation : 1;
	unsigned eventsWithLocation : 1;
	unsigned eventsWithMaybeLocation : 1;
	unsigned visitLMPLocation : 1;
	unsigned visitLocation : 1;
	unsigned visitMaybeLocation : 1;
} SCD_Struct_AW11;

typedef struct {
	int list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_AW12;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectDuration : 1;
	unsigned connectionType : 1;
	unsigned currentNatType : 1;
	unsigned isVideo : 1;
	unsigned localNetworkConnection : 1;
	unsigned onLockScreen : 1;
	unsigned relayConnectDuration : 1;
	unsigned remoteNatType : 1;
	unsigned remoteNetworkConnection : 1;
	unsigned usesRelay : 1;
} SCD_Struct_AW13;

typedef struct {
	unsigned timestamp : 1;
	unsigned backCameraCaptureDuration : 1;
	unsigned callDuration : 1;
	unsigned conferenceMiscError : 1;
	unsigned connectDuration : 1;
	unsigned connectionType : 1;
	unsigned currentNatType : 1;
	unsigned dataRate : 1;
	unsigned diagnosticPingAvg : 1;
	unsigned diagnosticPingMax : 1;
	unsigned diagnosticPingMin : 1;
	unsigned diagnosticPingPacketLoss : 1;
	unsigned endedReason : 1;
	unsigned frontCameraCaptureDuration : 1;
	unsigned gameKitError : 1;
	unsigned genericError : 1;
	unsigned gksError : 1;
	unsigned gksReturnCode : 1;
	unsigned invitationServiceError : 1;
	unsigned isAudioInterrupted : 1;
	unsigned isCallUpgrade : 1;
	unsigned isInitiator : 1;
	unsigned isNetworkActive : 1;
	unsigned isNetworkEnabled : 1;
	unsigned isNetworkReachable : 1;
	unsigned isVideo : 1;
	unsigned isVideoInterrupted : 1;
	unsigned linkQuality : 1;
	unsigned localNetworkConnection : 1;
	unsigned messageDeliveryError : 1;
	unsigned networkCheckResult : 1;
	unsigned onLockScreen : 1;
	unsigned registrationError : 1;
	unsigned relayConnectDuration : 1;
	unsigned relayError : 1;
	unsigned remoteNatType : 1;
	unsigned remoteNetworkConnection : 1;
	unsigned usesRelay : 1;
	unsigned viceroyError : 1;
} SCD_Struct_AW14;

typedef struct {
	unsigned timestamp : 1;
	unsigned interruptionDuration : 1;
	unsigned isAudioResumed : 1;
	unsigned isVideo : 1;
	unsigned isVideoResumed : 1;
	unsigned linkQuality : 1;
	unsigned onLockScreen : 1;
} SCD_Struct_AW15;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned genericError : 1;
	unsigned isDSUser : 1;
	unsigned isPhoneUser : 1;
	unsigned pOSIXError : 1;
	unsigned registrationError : 1;
	unsigned resultCode : 1;
	unsigned success : 1;
	unsigned uRLError : 1;
} SCD_Struct_AW16;

typedef struct {
	unsigned timestamp : 1;
	unsigned clientType : 1;
	unsigned durationOfSession : 1;
	unsigned durationToConnect : 1;
	unsigned endedReason : 1;
	unsigned isCellularInterfaceDisallowed : 1;
	unsigned isInitiator : 1;
	unsigned isLegacySessionType : 1;
	unsigned isNetworkActive : 1;
	unsigned isNetworkEnabled : 1;
	unsigned isNetworkReachable : 1;
	unsigned isQREnabled : 1;
	unsigned isUsingQRDirectly : 1;
	unsigned isWifiInterfaceDisallowed : 1;
	unsigned isWithDefaultPairedDevice : 1;
	unsigned linkProtocol : 1;
	unsigned sessionProtocolVersionNumber : 1;
	unsigned transportType : 1;
} SCD_Struct_AW17;

typedef struct {
	unsigned timestamp : 1;
	unsigned callDuration : 1;
	unsigned conferenceMiscError : 1;
	unsigned connectDuration : 1;
	unsigned connectionType : 1;
	unsigned currentNatType : 1;
	unsigned dataRate : 1;
	unsigned endedReason : 1;
	unsigned gameKitError : 1;
	unsigned genericError : 1;
	unsigned gksError : 1;
	unsigned gksReturnCode : 1;
	unsigned isInitiator : 1;
	unsigned isNetworkActive : 1;
	unsigned isNetworkEnabled : 1;
	unsigned isNetworkReachable : 1;
	unsigned linkQuality : 1;
	unsigned localNetworkConnection : 1;
	unsigned networkCheckResult : 1;
	unsigned relayConnectDuration : 1;
	unsigned remoteNatType : 1;
	unsigned remoteNetworkConnection : 1;
	unsigned usesRelay : 1;
} SCD_Struct_AW18;

typedef struct {
	unsigned timestamp : 1;
	unsigned attachmentSize : 1;
	unsigned connectionType : 1;
	unsigned downloadDuration : 1;
	unsigned firstLevelMMCSError : 1;
	unsigned fourthLevelMMCSError : 1;
	unsigned fzError : 1;
	unsigned genericError : 1;
	unsigned linkQuality : 1;
	unsigned messageError : 1;
	unsigned secondLevelMMCSError : 1;
	unsigned thirdLevelMMCSError : 1;
	unsigned tokenError : 1;
} SCD_Struct_AW19;

typedef struct {
	unsigned list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_AW20;

typedef struct {
	unsigned connectEndToRequestStartMillis : 1;
	unsigned connectStartToConnectEndMillis : 1;
	unsigned connectStartToSecureConnectionStartMillis : 1;
	unsigned domainLookupEndToConnectStartMillis : 1;
	unsigned domainLookupStartToDomainLookupEndMillis : 1;
	unsigned errorCode : 1;
	unsigned fetchStartToDomainLookupStartMillis : 1;
	unsigned navigationStartToRedirectStartMillis : 1;
	unsigned redirectEndToFetchStartMillis : 1;
	unsigned redirectStartToRedirectEndMillis : 1;
	unsigned requestStartToResponseStartMillis : 1;
	unsigned responseStartToResponseEndMillis : 1;
	unsigned secureConnectionStartToConnectEndMillis : 1;
	unsigned timestamp : 1;
} SCD_Struct_AW21;

typedef struct {
	long long list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_AW22;

typedef struct {
	unsigned bytesReceived : 1;
	unsigned bytesSent : 1;
	unsigned clientConnectionCount : 1;
	unsigned connectionDuration : 1;
	unsigned timestamp : 1;
	unsigned connectionAttemptCount : 1;
	unsigned connectionCellularFallbackCount : 1;
	unsigned connectionFailureCount : 1;
	unsigned connectionSuccessMptcpCount : 1;
	unsigned connectionSuccessTcpCount : 1;
	unsigned resumptionFailureCount : 1;
	unsigned resumptionSuccessCount : 1;
	unsigned suspensionCount : 1;
	unsigned upgradeSuccessAndNotNeededCount : 1;
	unsigned upgradeSuccessAndPrimaryCount : 1;
} SCD_Struct_AW23;

typedef struct {
	unsigned interfaceType : 1;
	unsigned ipProtocol : 1;
	unsigned tcpECNIntClientSetup : 1;
	unsigned tcpECNIntClientSuccess : 1;
	unsigned tcpECNIntConnNoPLCE : 1;
	unsigned tcpECNIntConnPLCE : 1;
	unsigned tcpECNIntConnPLNoCE : 1;
	unsigned tcpECNIntConnRecvCE : 1;
	unsigned tcpECNIntConnRecvECE : 1;
	unsigned tcpECNIntFallbackCE : 1;
	unsigned tcpECNIntFallbackReorder : 1;
	unsigned tcpECNIntFallbackSynLoss : 1;
	unsigned tcpECNIntNotSupportedPeer : 1;
	unsigned tcpECNIntOffAvgRTT : 1;
	unsigned tcpECNIntOffDropRst : 1;
	unsigned tcpECNIntOffDropRxmt : 1;
	unsigned tcpECNIntOffOOBPer : 1;
	unsigned tcpECNIntOffRTTVar : 1;
	unsigned tcpECNIntOffReorderPer : 1;
	unsigned tcpECNIntOffRxmtPer : 1;
	unsigned tcpECNIntOffSACKE : 1;
	unsigned tcpECNIntOffTotalOOPkts : 1;
	unsigned tcpECNIntOffTotalRxPkts : 1;
	unsigned tcpECNIntOffTotalRxmtPkts : 1;
	unsigned tcpECNIntOffTotalTxPkts : 1;
	unsigned tcpECNIntOnAvgRTT : 1;
	unsigned tcpECNIntOnDropRst : 1;
	unsigned tcpECNIntOnDropRxmt : 1;
	unsigned tcpECNIntOnOOBPer : 1;
	unsigned tcpECNIntOnRTTVar : 1;
	unsigned tcpECNIntOnReorderPer : 1;
	unsigned tcpECNIntOnSACKE : 1;
	unsigned tcpECNIntOnTotalOOPkts : 1;
	unsigned tcpECNIntOnTotalRxPkts : 1;
	unsigned tcpECNIntOnTotalRxmtPkts : 1;
	unsigned tcpECNIntOnTotalTxPkts : 1;
	unsigned tcpECNIntRecvCE : 1;
	unsigned tcpECNIntRecvECE : 1;
	unsigned tcpECNIntRxmtPer : 1;
	unsigned tcpECNIntSentECE : 1;
	unsigned tcpECNIntServerSetup : 1;
	unsigned tcpECNIntServerSuccess : 1;
	unsigned tcpECNIntSynAckLost : 1;
	unsigned tcpECNIntSynLost : 1;
	unsigned tcpECNIntTotalConnections : 1;
	unsigned tcpUnsentDataAtSleepCnt : 1;
} SCD_Struct_AW24;

typedef struct {
	unsigned tcpECNClientSetup : 1;
	unsigned tcpECNClientSuccess : 1;
	unsigned tcpECNConnNoPacketLossCE : 1;
	unsigned tcpECNConnPacketLossCE : 1;
	unsigned tcpECNConnPacketLossNoCE : 1;
	unsigned tcpECNConnRecvCE : 1;
	unsigned tcpECNConnRecvECE : 1;
	unsigned tcpECNFallbackCE : 1;
	unsigned tcpECNFallbackReorder : 1;
	unsigned tcpECNFallbackSynLoss : 1;
	unsigned tcpECNNotSupportedPeer : 1;
	unsigned tcpECNRecvCE : 1;
	unsigned tcpECNRecvECE : 1;
	unsigned tcpECNSentECE : 1;
	unsigned tcpECNServerSetup : 1;
	unsigned tcpECNServerSuccess : 1;
	unsigned tcpECNSynAckLost : 1;
	unsigned tcpECNSynLost : 1;
	unsigned tcpECNClientNegotiationEnabled : 1;
	unsigned tcpECNServerNegotiationEnabled : 1;
} SCD_Struct_AW25;

typedef struct {
	unsigned connectedAddressIndex : 1;
	unsigned connectionReuseCount : 1;
	unsigned dataStallCount : 1;
	unsigned flowConnectMilliseconds : 1;
	unsigned flowDurationMilliseconds : 1;
	unsigned ipv4AddressCount : 1;
	unsigned ipv6AddressCount : 1;
	unsigned pathTriggerMilliseconds : 1;
	unsigned proxyMilliseconds : 1;
	unsigned resolutionMilliseconds : 1;
	unsigned timestamp : 1;
	unsigned tlsMilliseconds : 1;
	unsigned trafficClass : 1;
	unsigned connectedAddressFamily : 1;
	unsigned connectedInterfaceType : 1;
	unsigned connectionMode : 1;
	unsigned failureReason : 1;
	unsigned firstAddressFamily : 1;
	unsigned usedProxyType : 1;
	unsigned customProxyConfigured : 1;
	unsigned fallbackEligible : 1;
	unsigned multipathConfigured : 1;
	unsigned resolutionRequired : 1;
	unsigned synthesizedIPv6Address : 1;
	unsigned systemProxyConfigured : 1;
	unsigned tfoConfigured : 1;
	unsigned tlsConfigured : 1;
	unsigned triggeredPath : 1;
	unsigned usedFallback : 1;
	unsigned weakFallback : 1;
} SCD_Struct_AW26;

typedef struct {
	unsigned duration : 1;
	unsigned networkServiceType : 1;
	unsigned responseReceivedDuration : 1;
	unsigned startTime : 1;
	unsigned adaptiveTcpReadTimeout : 1;
	unsigned adaptiveTcpWriteTimeout : 1;
	unsigned errorCode : 1;
	unsigned httpStatus : 1;
	unsigned locatorPort : 1;
	unsigned qualityOfService : 1;
	unsigned requestSize : 1;
	unsigned responseSize : 1;
	unsigned allowsCellular : 1;
	unsigned allowsPowerNapScheduling : 1;
	unsigned cancelled : 1;
	unsigned connectionReused : 1;
	unsigned fastFail : 1;
	unsigned finalTryInRequest : 1;
	unsigned forceNondiscretionary : 1;
	unsigned inlineEdgeComplete : 1;
	unsigned powerPluggedInAtEnd : 1;
	unsigned powerPluggedInAtStart : 1;
	unsigned powerPluggedInWhenQueued : 1;
	unsigned proxyUsed : 1;
	unsigned requiresPowerPluggedIn : 1;
	unsigned timedOut : 1;
	unsigned transactionComplete : 1;
} SCD_Struct_AW27;

typedef struct {
	unsigned tcpiCellRxbytes : 1;
	unsigned tcpiCellRxpackets : 1;
	unsigned tcpiCellTxbytes : 1;
	unsigned tcpiCellTxpackets : 1;
	unsigned tcpiRxbytes : 1;
	unsigned tcpiRxduplicatebytes : 1;
	unsigned tcpiRxoutoforderbytes : 1;
	unsigned tcpiRxpackets : 1;
	unsigned tcpiSndBw : 1;
	unsigned tcpiTxbytes : 1;
	unsigned tcpiTxpackets : 1;
	unsigned tcpiTxretransmitbytes : 1;
	unsigned tcpiTxunacked : 1;
	unsigned tcpiWifiRxbytes : 1;
	unsigned tcpiWifiRxpackets : 1;
	unsigned tcpiWifiTxbytes : 1;
	unsigned tcpiWifiTxpackets : 1;
	unsigned tcpiFlags : 1;
	unsigned tcpiLastOutif : 1;
	unsigned tcpiOptions : 1;
	unsigned tcpiRcvMss : 1;
	unsigned tcpiRcvNxt : 1;
	unsigned tcpiRcvSpace : 1;
	unsigned tcpiRcvWscale : 1;
	unsigned tcpiRto : 1;
	unsigned tcpiRttbest : 1;
	unsigned tcpiRttcur : 1;
	unsigned tcpiRttvar : 1;
	unsigned tcpiSndCwnd : 1;
	unsigned tcpiSndMss : 1;
	unsigned tcpiSndNxt : 1;
	unsigned tcpiSndSbbytes : 1;
	unsigned tcpiSndSsthresh : 1;
	unsigned tcpiSndWnd : 1;
	unsigned tcpiSndWscale : 1;
	unsigned tcpiSrtt : 1;
	unsigned tcpiState : 1;
	unsigned tcpiSynrexmits : 1;
	unsigned tcpiUnused1 : 1;
	unsigned tcpiUnused2 : 1;
} SCD_Struct_AW28;

typedef struct {
	unsigned captivePresentCount : 1;
	unsigned connectionCount : 1;
	unsigned mptcpSuccessCount : 1;
	unsigned restrictedNetworkCount : 1;
	unsigned resultConnectionResetCount : 1;
	unsigned resultNetworkUnavailableCount : 1;
	unsigned resultResponseTimeoutCount : 1;
	unsigned resultSendFailureCount : 1;
	unsigned resultServerBusyCount : 1;
	unsigned resultServerDetachedCount : 1;
	unsigned resultServerInterruptCount : 1;
	unsigned resultServerOfflineCount : 1;
	unsigned resultServerOrphanedCount : 1;
	unsigned resultServerSessionExpiredCount : 1;
	unsigned resultServerUnreachableCount : 1;
	unsigned resultSuccessCount : 1;
	unsigned resultUnknownErrorCount : 1;
	unsigned tfoSuccessCount : 1;
	unsigned timestamp : 1;
	unsigned alternatePathCount : 1;
	unsigned captivePresentFailedCount : 1;
	unsigned exceededMssCount : 1;
	unsigned interfaceType : 1;
	unsigned protocolType : 1;
	unsigned restrictedNetworkFailedCount : 1;
} SCD_Struct_AW29;

typedef struct {
	unsigned timestamp : 1;
	unsigned wifi2P4GHzRxDuration : 1;
	unsigned wifi2P4GHzTxDuration : 1;
	unsigned wifi5GHz20MHzRxDuration : 1;
	unsigned wifi5GHz20MHzTxDuration : 1;
	unsigned wifi5GHz40MHzRxDuration : 1;
	unsigned wifi5GHz40MHzTxDuration : 1;
	unsigned wifi5GHz80MHzRxDuration : 1;
	unsigned wifi5GHz80MHzTxDuration : 1;
	unsigned wifiFRTSDuration : 1;
	unsigned wifiHsicActiveDuration : 1;
	unsigned wifiPcieL0Duration : 1;
	unsigned wifiPcieL10Duration : 1;
	unsigned wifiPcieL11Duration : 1;
	unsigned wifiPcieL12Duration : 1;
	unsigned wifiScanDuration : 1;
	unsigned wifiSleepDuration : 1;
	unsigned wifiTotalDuration : 1;
	unsigned wifiTotalPowerMicroWatt : 1;
} SCD_Struct_AW30;

typedef struct {
	unsigned txbyte : 1;
	unsigned txchit : 1;
	unsigned txcmiss : 1;
	unsigned txctl : 1;
	unsigned txerror : 1;
	unsigned txframe : 1;
	unsigned txnoassoc : 1;
	unsigned txnobuf : 1;
	unsigned txprshort : 1;
	unsigned txretrans : 1;
	unsigned txrunt : 1;
	unsigned txserr : 1;
} SCD_Struct_AW31;

typedef struct {
	unsigned timestamp : 1;
	unsigned akmSuites : 1;
	unsigned capabilities : 1;
	unsigned channel : 1;
	unsigned channelWidth : 1;
	unsigned flags : 1;
	unsigned gatewayARPHistory : 1;
	unsigned htASel : 1;
	unsigned htAmpduParams : 1;
	unsigned htExtended : 1;
	unsigned htInfo : 1;
	unsigned htTxBf : 1;
	unsigned mcastCipher : 1;
	unsigned phyMode : 1;
	unsigned reason : 1;
	unsigned securityType : 1;
	unsigned subreason : 1;
	unsigned ucastCipher : 1;
	unsigned vhtInfo : 1;
	unsigned wpaProtocol : 1;
	unsigned isInVol : 1;
	unsigned isLinkUp : 1;
} SCD_Struct_AW32;

typedef struct {
	unsigned rxBytes : 1;
	unsigned rxPackets : 1;
	unsigned timestamp : 1;
	unsigned txBytes : 1;
	unsigned txBytesBe : 1;
	unsigned txBytesBk : 1;
	unsigned txBytesVi : 1;
	unsigned txBytesVo : 1;
	unsigned txPackets : 1;
	unsigned txPacketsBe : 1;
	unsigned txPacketsBk : 1;
	unsigned txPacketsVi : 1;
	unsigned txPacketsVo : 1;
	unsigned avgCCA : 1;
	unsigned dataTransferRateMpbs : 1;
	unsigned effectiveDataTransferRateMpbs : 1;
	unsigned effectiveLinkRateMpbs : 1;
	unsigned linkLatencyMs : 1;
	unsigned linkOpenPct : 1;
	unsigned linkRateMbps : 1;
	unsigned lqm : 1;
} SCD_Struct_AW33;

typedef struct {
	unsigned gateOpenTime : 1;
	unsigned trafficWatchDuration : 1;
	unsigned trafficWatchTime : 1;
	unsigned arpFailureCount : 1;
	unsigned bcnPerSign : 1;
	unsigned bcnRcvs : 1;
	unsigned bcnSched : 1;
	unsigned dnsServersImpacted : 1;
	unsigned dnsServersTotal : 1;
	unsigned fwTxFail : 1;
	unsigned fwTxFrames : 1;
	unsigned fwTxPerSign : 1;
	unsigned fwTxRetrans : 1;
	unsigned gwArpExpiry : 1;
	unsigned netScore : 1;
	unsigned rssi : 1;
	unsigned rxFrames : 1;
	unsigned sympAwdCode : 1;
	unsigned sympSign : 1;
	unsigned trafficWatchRx : 1;
	unsigned trgDisc : 1;
	unsigned txFail : 1;
	unsigned txFrames : 1;
	unsigned txPerSign : 1;
	unsigned txRetrans : 1;
	unsigned usrImpact : 1;
	unsigned usrInput : 1;
	unsigned validState : 1;
} SCD_Struct_AW34;

typedef struct {
	unsigned timestamp : 1;
	unsigned count : 1;
	unsigned nCallActive : 1;
	unsigned nCallIdle : 1;
	unsigned nCellularGood : 1;
	unsigned nData : 1;
	unsigned nNegativeStatusUpdate : 1;
	unsigned nPositiveStatusUpdate : 1;
	unsigned nRunning : 1;
	unsigned nStationary : 1;
	unsigned nStatusUpdateDelayBin1 : 1;
	unsigned nStatusUpdateDelayBin2 : 1;
	unsigned nStatusUpdateDelayBin3 : 1;
	unsigned nStatusUpdateDelayBin4 : 1;
	unsigned nStatusUpdateDelayBin5 : 1;
	unsigned nStatusUpdateDelayBin6 : 1;
	unsigned nUnknownStatusUpdat : 1;
	unsigned nVehicular : 1;
	unsigned nVoice : 1;
	unsigned nWalking : 1;
	unsigned nWifiBadBcn : 1;
	unsigned nWifiBadLoad : 1;
	unsigned nWifiBadPER : 1;
	unsigned nWifiBadRSSI : 1;
	unsigned nWifiBadSNR : 1;
	unsigned nWifiBadTransportRTP : 1;
	unsigned nWifiBadTransportSymptom : 1;
	unsigned nWifiNotInit : 1;
	unsigned nWifiNotReady : 1;
} SCD_Struct_AW35;

typedef struct {
	unsigned lTECTRSRP : 1;
	unsigned lTERSRP : 1;
	unsigned timestamp : 1;
	unsigned wiFiRSSI : 1;
	unsigned wiFiSINR : 1;
	unsigned bBAudioErasures : 1;
	unsigned bBAudioPacketLoss : 1;
	unsigned bSSLoad : 1;
	unsigned beaconRate : 1;
	unsigned hOBool : 1;
	unsigned lTEDataLQM : 1;
	unsigned lTESINR : 1;
	unsigned lTETxPower : 1;
	unsigned lTEVoiceLQM : 1;
	unsigned latteDejitterBufferUnderflow : 1;
	unsigned latteErasures : 1;
	unsigned latteNominalJitterBufferSize : 1;
	unsigned latteRTPPacketLoss : 1;
	unsigned sessionId : 1;
	unsigned signalBar : 1;
	unsigned wiFiRxRetry : 1;
	unsigned wiFiTxPER : 1;
	unsigned aTMRegistrationState : 1;
	unsigned captiveNetwork : 1;
	unsigned hOCapability : 1;
	unsigned iPSecTunnelStatus : 1;
	unsigned iWLANStatus : 1;
	unsigned lTEQoSAvailable : 1;
	unsigned wOWEnabled : 1;
	unsigned wiFiBSSIDChange : 1;
	unsigned wiFiPreferred : 1;
} SCD_Struct_AW36;

