/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:57 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_nw_endpoint_flow <NWConcrete_nw_endpoint_mode_handler>
@end

