/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:14 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Frameworks/IMUtil.framework/IMUtil
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NSURLUtil : NSObject
+(id)queryStringToQueryDictionary:(id)arg1 ;
+(id)dictionaryToQueryString:(id)arg1 ;
@end

