/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:35:45 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/lib/libAXSpeechManager.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface AXEmojiUtilities : NSObject
+(id)stringByReplacingEmojiCharactersWithEmojiDescriptions:(id)arg1 stringForPauses:(id)arg2 language:(id)arg3 rangeReplacements:(id)arg4 appendEmojiSuffix:(BOOL)arg5 ;
@end

