/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 27, 2017 at 2:59:11 PM Japan Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/MobileSafari.app/PlugIns/Safari.wkbundle/Safari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Safari/MeasurementControllerBase.h>

@class NSTimer, NSArray;

@interface PageMemoryMeasurementController : MeasurementControllerBase {

	NSTimer* _waitForMemoryPressureHandler;
	NSArray* _pagesNeedingMemoryWarningSent;
	int _currentPageIndex;

}
-(void)_waitForMemoryPressureHandlerTimerFired:(id)arg1 ;
-(id)initWithPluginPageContextController:(id)arg1 pagesNeedingMemoryWarningSent:(id)arg2 ;
-(void)_doBeforePageLoad;
-(id)_memoryUsage:(BOOL)arg1 ;
-(void)_postPageLoadEnd;
@end

